import type, { Config } from 'tailwindcss';
const c,
  o,
  n,
  fig: Config = {
    d,
    a,
    r,
  kMode: ['class'],
    c,
    o,
    n,
  tent: ['./ app /**/*.{ts,tsx}', './ components /**/*.{ts,tsx}', './ pages /**/*.{ts,tsx}'],
    t,
    h,
    e,
  me: {
      e,
      x,
      t,
  end: {
        c,
        o,
        l,
  ors: {
          b,
          a,
          c,
  kground: 'h sl(v ar(-- background))',
          f,
          o,
          r,
  eground: 'h sl(v ar(-- foreground))',
          p,
          r,
          i,
  mary: {
            D,
            E,
            F,
  AULT: 'h sl(v ar(-- primary))',
            f,
            o,
            r,
  eground: 'h sl(v ar(-- primary - foreground))',
          },
          s,
          e,
          c,
  ondary: {
            D,
            E,
            F,
  AULT: 'h sl(v ar(-- secondary))',
            f,
            o,
            r,
  eground: 'h sl(v ar(-- secondary - foreground))',
          },
          m,
          u,
          t,
  ed: { D, E, F,
  AULT: 'h sl(v ar(-- muted))', f, o, r,
  eground: 'h sl(v ar(-- muted - foreground))' },
          a,
          c,
          c,
  ent: {
            D,
            E,
            F,
  AULT: 'h sl(v ar(-- accent))',
            f,
            o,
            r,
  eground: 'h sl(v ar(-- accent - foreground))',
          },
          d,
          e,
          s,
  tructive: {
            D,
            E,
            F,
  AULT: 'h sl(v ar(-- destructive))',
            f,
            o,
            r,
  eground: 'h sl(v ar(-- destructive - foreground))',
          },
          b,
          o,
          r,
  der: 'h sl(v ar(-- border))',
          i,
          n,
          p,
  ut: 'h sl(v ar(-- input))',
          r,
          i,
          n,
  g: 'h sl(v ar(-- ring))',
          c,
          a,
          r,
  d: { D, E, F,
  AULT: 'h sl(v ar(-- card))', f, o, r,
  eground: 'h sl(v ar(-- card - foreground))' },
          p,
          o,
          p,
  over: {
            D,
            E,
            F,
  AULT: 'h sl(v ar(-- popover))',
            f,
            o,
            r,
  eground: 'h sl(v ar(-- popover - foreground))',
          },
        },
        b,
        o,
        r,
  derRadius: {
          l,
          g: 'v ar(-- radius)',
          m,
          d: 'c alc(v ar(-- radius) - 2px)',
          s,
          m: 'c alc(v ar(-- radius) - 4px)',
        },
        k,
        e,
        y,
  frames: {
          'accordion - down': {
            f,
            r,
            o,
  m: { h, e, i,
  ght: '0' },
            t,
            o: { h, e, i,
  ght: 'v ar(-- radix - accordion - content - height)' },
          },
          'accordion - up': {
            f,
            r,
            o,
  m: { h, e, i,
  ght: 'v ar(-- radix - accordion - content - height)' },
            t,
            o: { h, e, i,
  ght: '0' },
          },
        },
        a,
        n,
        i,
  mation: {
          'accordion - down': 'accordion - down 0.2s ease - out',
          'accordion - up': 'accordion - up 0.2s ease - out',
        },
      },
    },
    p,
    l,
    u,
  gins: [r equire('tailwindcss - animate')],
  };
export default config;
