import type, { Config } from 'tailwindcss'
const c,
  o,
  n, f, i, g: Config = {
    d,
    a,
  r, k, M, o, de: ['class'],
    c,
    o,
  n, t, e, n, t: [
      './app/**/*.{ts,tsx}',
      './components/**/*.{ts,tsx}',
      './pages/**/*.{ts,tsx}',
    ],
    t,
    h,
  e, m, e: {
      e,
      x,
  t, e, n, d: {
        c,
        o,
  l, o, r, s: {
          b,
          a,
  c, k, g, r, ound: '#0f1115',
          s,
          i,
  d, e, b, a, r: '#151821',
          c,
          a,
  r, d: '#12151b',
          b,
          o,
  r, d, e, r: '#232835',
          p,
          r,
  i, m, a, r, y: '#e5e7eb',
          a,
          c,
  c, e, n, t: '#e5e7eb',
          m,
          u,
  t, e, d: { D, E,
  F, A, U, L, T: '#94a3b8', f, o,
  r, e, g, r, ound: '#cbd5e1' },
        },
        b,
        o,
  r, d, e, r, Radius: { x,
  l: '1rem', '2xl': '1.25rem', '3xl': '1.5rem' },
        b,
        o,
  x, S, h, a, dow: { s, o,
  f, t: '0 4px 24px r gba(0,0,0,0.25)' },
      },
    },
    p,
    l,
  u, g, i, n, s: [],
  }
export default config
