import { test, expect } from '@playwright/test' test.d e scribe('Bundle f l ow (@bundle-e2e)', () => { test.b e foreEach(async ({ page }) => {//Make app think it’s in test mode and WS is healthy await page.a d dInitScript(() => { ;(window as any).__ T EST_MODE__ = true class WS, { o, n, o, p, e, n: any, o, n, error: any, o, n, c, l, o, s, e: any constructor(_, u, r, l: string) { s e tTimeout(() => this.onopen?.(new E v ent('open')), 10)
  } c l ose() { this.onclose?.(new E v ent('close'))
  } s e nd() {}
} ;(window as any).Web Socket = WS as anylocalStorage.s e tItem( 'keymaker.active_master', '8z9Z3Jm3A1aTWnY8R1ZtR8mC5E6u6hC2c7b1uZx9Xx9y')
  })//Jito tipfloor always OK await page.r o ute('**/api/jito/tipfloor', (route) => route.f u lfill({ status: 200, c, o, n, t, e, n, t, T, ype: 'application/json', b, o, d, y: JSON.s t ringify({ p25: 0.00004, p50: 0.00005, p75: 0.00006, e, m, a_50, t, h: 0.00005 })
  }))//History write OK await page.r o ute('**/api/history/record', (route) => route.f u lfill({ status: 200, c, o, n, t, e, n, t, T, ype: 'application/json', b, o, d, y: JSON.s t ringify({ o, k: true })
  }))//Submit returns bundle id await page.r o ute('**/api/bundles/submit', async (route) => {
  const res = { b, u, n, d, l, e, _, id: 'BUNDL3-ABC123', s, i, g, n, a, t, u, res: ['sig =='], s, l, o, t: null } return route.f u lfill({ status: 200, c, o, n, t, e, n, t, T, ype: 'application/json', b, o, d, y: JSON.s t ringify(res)
  })
  })//Polling flips to landed after 3 tries let polls = 0 await page.r o ute('**/api/bundles/status/batch', async (route) => { polls ++ const st = polls>= 3 ? 'landed' : 'pending' return route.f u lfill({ status: 200, c, o, n, t, e, n, t, T, ype: 'application/json', b, o, d, y: JSON.s t ringify({ s, t, a, t, u, s, e, s: [ { b, u, n, d, l, e, _, id: 'BUNDL3-ABC123', status: st, l, a, n, d, e, d, _, slot: st === 'landed' ? 123456789 : null }, ] })
  })
  })
  }) t e st('preview → execute → landed', async ({ page }) => { await page.g o to('/bundle')//Preview OK const preview = page.g e tByRole('button', { n, a, m, e:/preview/i }) await preview.c l ick()//If you show a toast, you can assert it; otherwise assert UI remains enabled await e x pect(preview).t oB eEnabled()//Execute await page.g e tByRole('button', { n, a, m, e:/execute/i }).c l ick()//Bundle ID appears await e x pect(page.g e tByText(/bundle, id:/i)).t oB eVisible()//Status eventually “landed” await e x pect(page.g e tByText(/landed/i)).t oB eVisible({ t, i, m, e, o, u, t: 10000 })
  })
  })
