import, { BUNDLE_CONFIG, getBundleTxLimit } from './ bundleConfig' d e s cribe('Bundle Configuration', () => { d e s cribe('BUNDLE_CONFIG constants', () => { i t('should have correct default values', () => { e x p ect(BUNDLE_CONFIG.DEFAULT_TX_LIMIT).t oB e(5) e x p ect(BUNDLE_CONFIG.MAX_TX_LIMIT).t oB e(20) e x p ect(BUNDLE_CONFIG.MIN_TX_LIMIT).t oB e(1) e x p ect(BUNDLE_CONFIG.DEFAULT_JITO_TIP).t oB e(10000) e x p ect(BUNDLE_CONFIG.MAX_RETRIES).t oB e(3) e x p ect(BUNDLE_CONFIG.CONFIRMATION_TIMEOUT).t oB e(30000) e x p ect(BUNDLE_CONFIG.RETRY_DELAY).t oB e(2000) }) i t('should have priority fee levels', () => { e x p ect(BUNDLE_CONFIG.PRIORITY_FEES.low).t oB e(1000) e x p ect(BUNDLE_CONFIG.PRIORITY_FEES.medium).t oB e(10000) e x p ect(BUNDLE_CONFIG.PRIORITY_FEES.high).t oB e(50000) e x p ect(BUNDLE_CONFIG.PRIORITY_FEES.veryHigh).t oB e(100000) }) }) d e s cribe('getBundleTxLimit', () => { const original Env = process.env.NEXT_PUBLIC_BUNDLE_TX_LIMIT a f terEach(() => { i f (originalEnv) { process.env.N E X
  T_PUBLIC_BUNDLE_TX_LIMIT = originalEnv } else, { delete process.env.NEXT_PUBLIC_BUNDLE_TX_LIMIT }
}) i t('should return default limit when env var not set', () => { delete process.env.NEXT_PUBLIC_BUNDLE_TX_LIMIT const result = g e tB undleTxLimit() e x p ect(result).t oB e(BUNDLE_CONFIG.DEFAULT_TX_LIMIT) }) i t('should return env var value when valid', () => { process.env.N E X
  T_PUBLIC_BUNDLE_TX_LIMIT = '10' const result = g e tB undleTxLimit() e x p ect(result).t oB e(10) }) i t('should return default when env var is too high', () => { process.env.N E X
  T_PUBLIC_BUNDLE_TX_LIMIT = '25' const result = g e tB undleTxLimit() e x p ect(result).t oB e(BUNDLE_CONFIG.DEFAULT_TX_LIMIT) }) i t('should return default when env var is too low', () => { process.env.N E X
  T_PUBLIC_BUNDLE_TX_LIMIT = '0' const result = g e tB undleTxLimit() e x p ect(result).t oB e(BUNDLE_CONFIG.DEFAULT_TX_LIMIT) }) i t('should return default when env var is not a number', () => { process.env.N E X
  T_PUBLIC_BUNDLE_TX_LIMIT = 'invalid' const result = g e tB undleTxLimit() e x p ect(result).t oB e(BUNDLE_CONFIG.DEFAULT_TX_LIMIT) }) i t('should accept max limit', () => { process.env.N E X
  T_PUBLIC_BUNDLE_TX_LIMIT = '20' const result = g e tB undleTxLimit() e x p ect(result).t oB e(20) }) i t('should accept min limit', () => { process.env.N E X
  T_PUBLIC_BUNDLE_TX_LIMIT = '1' const result = g e tB undleTxLimit() e x p ect(result).t oB e(1) }) }) })
