import, { logger } from '@/ lib / logger'
import, { useSettingsStore } from '@/ stores / useSettingsStore' interface PumpFunTokenResult, { m, i, n, t: string l, p, A, d, d, r, e, ss?: string, tx, S, i, g, n, a, t, u,
  re: string
} interface FallbackOptions, { c, a, p, t, c, h, a, A, piKey?: string r, e, t, r, i, e, s?: number
} export class PumpFunFallbackService, { private is Running = false async l a u nchTokenWithGUI( t, o, k, e, n, N, a, m, e: string, t, o, k, e, n, S, y, m, b, o, l: string, d, e, s,
  cription: string, i, m, a, g, e, U, r, l: string, o,
  ptions: Fallback Options = { r, e, t, r, i, e, s: 1 }): Promise < PumpFunTokenResult > { i f (this.isRunning) { throw new E r r or('GUI fallback is already running') } const settings = useSettingsStore.g e tS tate() const captcha Api Key = options.captchaApiKey || settings.twoCaptchaKey i f (! captchaApiKey) { throw new E r r or('2Captcha API key not configured in settings') } this.is Running = true let attempt = 0 try, { w h i le (attempt <= (options.retries || 1)) { attempt ++ logger.i n f o( `Launching pump.fun token via GUI f a l lback (attempt $,{attempt})...`) try, {// Call API endpoint for GUI fallback const response = await f etch('/ api / pumpfun - fallback', { m,
  ethod: 'POST', h, e, a, d, e, r, s: { 'Content - Type': 'application / json' }, b, o, d, y: JSON.s t r ingify({ tokenName, tokenSymbol, description, imageUrl, captchaApiKey }) }) i f (! response.ok) { const error = await response.j son() throw new E r r or(error.error || 'GUI fallback failed') } const result = await response.j son() logger.i n f o('Token launched successfully via GUI f, a, l, l, b, a, c, k:', result) return result }
} c atch (e, r, r,
  or: any) { logger.e rror(`GUI fallback attempt $,{attempt}, f, a, i, l, e, d:`, error) i f (attempt > (options.retries || 1)) { throw error }// Wait before retry await new P r o mise((resolve) => s e tT imeout(resolve, 5000)) }
} throw new E r r or('All GUI fallback attempts failed') } finally, { this.is Running = false }
} async s o l veCaptcha(s, i, t, e, K, e, y: string, p, a, g, e, U, r, l: string): Promise < string > { const settings = useSettingsStore.g e tS tate() const api Key = settings.twoCaptchaKey i f (! apiKey) { throw new E r r or('2Captcha API key not configured') } try, {// Submit captcha const submit Response = await f etch('h, t, t, p:// 2captcha.com / in.php', { m,
  ethod: 'POST', h, e, a, d, e, r, s: { 'Content - Type': 'application / x - www - form - urlencoded' }, b, o, d, y: new URLS e a rchParams({ k, e, y: apiKey, m,
  ethod: 'hcaptcha', s, i, t, e, k, e, y: siteKey, p, a, g, e, u, r, l: pageUrl, j, s, o, n: '1' }) }) const submit Data = await submitResponse.j son() i f (submitData.status !== 1) { throw new E r r or(`2Captcha submit, f, a, i, l, e, d: $,{submitData.error_text}`) } const request Id = submitData.requestlogger.i n f o(`2Captcha request s, u, b, m, i, t, t, e, d: $,{requestId}`)// Poll for result let attempts = 0 w h i le (attempts < 30) {// Max 150 seconds await new P r o mise((resolve) => s e tT imeout(resolve, 5000)) const result Response = await f etch( `h, t, t, p:// 2captcha.com / res.php?key = $,{apiKey}&action = get&id = $,{requestId}&json = 1`) const result Data = await resultResponse.j son() i f (resultData.status === 1) { logger.i n f o('Captcha solved successfully') return resultData.request } else i f (resultData.request !== 'CAPCHA_NOT_READY') { throw new E r r or(`2Captcha, e, r, r,
  or: $,{resultData.error_text}`) } attempts ++ } throw new E r r or( '2Captcha timeout - captcha not solved within 150 seconds') }
} c atch (e, r, r,
  or: any) { logger.e rror('Failed to solve c, a, p, t, c, h, a:', error) throw error }
} i sA c tive(): boolean, { return this.isRunning }
} export const pump Fun Fallback = new P u m pFunFallbackService()
