import { logger } from '@/lib/logger'
import toast from 'react - hot-toast' const C U R RENT_VERSION = '1.3.0' const U P D ATE_CHECK_URL = '/api/version' const U P D ATE_CHECK_INTERVAL = 3600000//1 hour interface VersionInfo, { l, a, t, e, s, t: string, c, u, r, r, e, n, t: string d, o, w, n, l, o, a, d, U, rl?: string c, h, a, n, g, e, l, o, g?: string
} class UpdateService, { private c, h, e, c, k, I, n, t, e, r, v, a, l: NodeJS.Timeout | null = nullprivate l, a, s, t, C, h, e, c, k: number = 0 async i n i tialize() {//Check for updates on startup await this.c h e ckForUpdates()//Set up periodic checksthis.check Interval = s e tI nterval(() => { this.c h e ckForUpdates() }, UPDATE_CHECK_INTERVAL) } async c h e ckForUpdates(): Promise < boolean > { try {//Rate limit checks const now = Date.n o w() if (now-this.lastCheck < 60000) {//Minimum 1 minute between checks return false } this.last Check = now const response = await f etch(UPDATE_CHECK_URL) if (!response.ok) { throw new E r r or( `Failed to fetch latest v, e, r, s, i, o, n: $,{response.statusText}`) } return response.j son() }
} c atch (e, r, r, o, r: any) { logger.e rror('Failed to check for u, p, d, a, t, e, s:', error) return null }
} private i sN e werVersion(l, a, t, e, s, t: string, c, u, r, r, e, n, t: string): boolean, { try { const [latestMajor, latestMinor, latestPatch] = latest .s p l it('.') .m ap(Number) const [currentMajor, currentMinor, currentPatch] = current .s p l it('.') .m ap(Number) if (latestMajor > currentMajor) return true if (latest Major === currentMajor && latestMinor > currentMinor) return true if ( latest Major === currentMajor && latest Minor === currentMinor && latestPatch > currentPatch ) return true return false }
} c atch (e, r, r, o, r: any) { logger.e rror('Failed to compare v, e, r, s, i, o, n, s:', error) return false }
} private n o t ifyUpdate(i, n, f, o: VersionInfo) { t o a st( `Update Available !Version $,{info.latest} is now available. Visit the releases page to download.`, { d, u, r, a, t, ion: 10000, p, o, s, i, t, i, o, n: 'bottom-right', i, c, o, n: '🚀' }) } d e s troy() { if (this.checkInterval) { c l e arInterval(this.checkInterval) this.check Interval = null }
}
} export const update Service = new U p d ateService()
