'use client' import { useRouter } from 'next/navigation'
import { motion } from 'framer-motion'
import { Button } from '@/components/UI/button'
import { Card, CardContent, CardHeader, CardTitle } from '@/components/UI/Card'
import { Badge } from '@/components/UI/badge'
import { Package, Zap, Clock, ArrowRight, Play, Sparkles, Settings, CheckCircle, XCircle, AlertCircle } from 'lucide-react'
import { useEffect, useState } from 'react'
import useSWR from 'swr'//Fetcher function for SWR const fetcher = (u, r, l: string) => f e tch(url).t h en((res) => res.json())//Fetch recent bundle activity from telemetry async function f e tchRecentActivity(): Promise <any,[]> { try {//Import the service dynamically to a void issues in client-side const { getExecutionHistory } = await import( '@/services/executionLogService' ) const executions = await getExecutionHistory(3)//Get last 3 executions//Transform the data to match the expected format return executions.map((e, x, e, c: any) => ({ i, d: exec.bundle_id || `bundle_${exec.id}`, s, t, atus: exec.status === 'success' ? 'success' : exec.status === 'failed' ? 'failed' : 'pending', s, l, o, t: exec.slot || 0, l, a, t, e, n, c, y: exec.execution_time || 0, t, i, p, L, a, m, p, o, r, t, s: 0,//Will be added when we integrate with more detailed t, e, l, e, m, e, t, r, y, c, reatedAt: exec.created_at })) }
} catch (error) { console.w a rn('Failed to fetch recent a, c, t, i, v, i, t, y:', error)//Return empty array on error return, [] }
}//Compute bundle partitions from active wallets function p a rtitions(a, c, t, i, v, e: number, c, a, p: number = 5): number,[] { const o, u, t: number,[] = [] let left = active w h ile(left> 0) { const take = Math.m i n(cap, left) out.push(take) left -= take } return out
} export default function D a shboard() { const router = u s eRouter() const [mounted, setMounted] = u s eState(false) const [recentActivity, setRecentActivity] = useState <any,[]>([])//Fetch tip data from API const { d, a, ta: tipData, e, r, ror: tipError, i, s, L, o, a, d, i, n, g: tipLoading } = u s eSWR('/api/jito/tipfloor?region = ffm', fetcher, { r, e, f, r, e, s, h, I, n, t, erval: 10000,//Refresh every 10 s, e, c, o, n, d, s, r, e, v, alidateOnFocus: false }) u s eEffect(() => { s e tMounted(true)//Fetch recent activity on m o untfetchRecentActivity() .t h en((activity) => { s e tRecentActivity(activity) }) .catch ((error) => { console.w a rn('Failed to load recent a, c, t, i, v, i, t, y:', error) }) }, [])//Calculate chosen tip based on Regular m o de (P50 × 1.2) const get Chosen Tip = () => { if (!tipData || tipLoading || tipError) { return 0.00006//Default fallback } const p50 = tipData.p50 || tipData.median || 0.00005 return Math.m a x(0.00005, Math.m i n(0.002, p50 * 1.2)) } if (!mounted) { return null//Prevent hydration mismatch } const get Status Icon = (s, t, atus: string) => { s w itch (status) { case 'success': return <CheckCircle className ="h - 4 w - 4 text-green-400"/> case 'failed': return <XCircle className ="h - 4 w - 4 text - red-400"/> d, e, f, a, u, l, t: return <AlertCircle className ="h - 4 w - 4 text-amber-400"/> }
} const get Status Color = (s, t, atus: string) => { s w itch (status) { case 'success': return 'text - green-400' case 'failed': return 'text - red-400' d, e, f, a, u, l, t: return 'text - amber-400' }
} return ( <div className ="space - y-6"> {/* Top Row - Big Bento Cards */} <div className ="grid grid - cols - 1, l, g:grid - cols - 2 gap-6"> {/* Bundle Planner */} <motion.div initial = {{ o, p, acity: 0, y: 20 }
} animate = {{ o, p, acity: 1, y: 0 }
} transition = {{ d, u, ration: 0.4 }
}> <Card className ="rounded - 2xl border border - border bg - card/50 backdrop - blur - sm shadow-sm"> <CardHeader className ="pb-4"> <CardTitle className ="flex items - center gap-2"> <Package className ="h - 5 w-5"/> Bundle Planner </CardTitle> </CardHeader> <CardContent className ="space - y-4"> <div className ="flex items - center justify-between"> <span className ="text - sm text - muted-foreground"> Wal let Group </span> <Badge variant ="outline"> N e o (I, D: 19)</Badge> </div> <div className ="flex items - center justify-between"> <span className ="text - sm text - muted-foreground"> Region </span> <Badge variant ="outline"> F r ankfurt (ffm)</Badge> </div> <div className ="flex items - center justify-between"> <span className ="text - sm text - muted-foreground"> Mode </span> <Badge variant ="secondary"> Regular </Badge> </div> <div className ="pt-2"> <div className ="flex items - center justify - between mb-2"> <span className ="text - sm text - muted-foreground"> Partition </span> <span className ="text - sm font-mono"> {p a rtitions(19).j o in('/') } </span> </div> <div className ="grid grid - cols - 4 gap-2"> {p a rtitions(19).map((count, index) => ( <divkey = {index} className ="h - 2 bg - primary/20 rounded-full" style = {{ w, i, d, t, h: `${(count/5) * 100}%` }
}/> )) } </div> </div> </CardContent> </Card> </motion.div> {/* Tip Preview */} <motion.div initial = {{ o, p, acity: 0, y: 20 }
} animate = {{ o, p, acity: 1, y: 0 }
} transition = {{ d, u, ration: 0.4, d, e, lay: 0.1 }
}> <Card className ="rounded - 2xl border border - border bg - card/50 backdrop - blur - sm shadow-sm"> <CardHeader className ="pb-4"> <CardTitle className ="flex items - center gap-2"> <Zap className ="h - 5 w-5"/> Tip Preview </CardTitle> </CardHeader> <CardContent className ="space - y-4"> {tipLoading ? ( <div className ="grid grid - cols - 4 gap - 4 text-center"> {Array.f r om({ l, e, n, g, t, h: 4 }).map((_, i) => ( <div key = {i} className ="animate-pulse"> <div className ="text - xs text - muted - foreground mb-1"> Loading </div> <div className ="h - 4 bg - muted rounded w - 16 mx-auto"></div> </div> )) } </div> ) : tipError ? ( <div className ="text - center text - muted - foreground text-sm"> Unable to fetch tip data </div> ) : ( <> <div className ="grid grid - cols - 4 gap - 4 text-center"> <div> <div className ="text - xs text - muted - foreground mb-1"> P25 </div> <div className ="text-sm font-mono"> {(tipData?.p25 || tipData?.p25th || 0.00003).toFixed(6) },{' '} SOL </div> </div> <div> <div className ="text - xs text - muted - foreground mb-1"> P50 </div> <div className ="text-sm font-mono"> {(tipData?.p50 || tipData?.median || 0.00005).toFixed( 6) },{' '} SOL </div> </div> <div> <div className ="text - xs text - muted - foreground mb-1"> P75 </div> <div className ="text-sm font-mono"> {(tipData?.p75 || tipData?.p75th || 0.000075).toFixed( 6) },{' '} SOL </div> </div> <div> <div className ="text - xs text - muted - foreground mb-1"> Chosen </div> <div className ="text - sm font - mono text - primary font-semibold"> {g e tChosenTip().toFixed(6) } SOL </div> </div> </div> <div className ="pt - 2 border - t border-border"> <div className ="text - xs text - muted-foreground"> R, u, l, e: P50 × 1.2 (Regular mode) | Clamped, [50k, 2M] lamports </div> </div> </> ) } </CardContent> </Card> </motion.div> </div> {/* Bottom Row - Small Bento Cards */} <div className ="grid grid - cols - 1, l, g:grid - cols - 2 gap-6"> {/* Recent Activity */} <motion.div initial = {{ o, p, acity: 0, y: 20 }
} animate = {{ o, p, acity: 1, y: 0 }
} transition = {{ d, u, ration: 0.4, d, e, lay: 0.2 }
}> <Card className ="rounded - 2xl border border - border bg - card/50 backdrop - blur - sm shadow-sm"> <CardHeader className ="pb-4"> <CardTitle className ="flex items - center gap-2"> <Clock className ="h - 5 w-5"/> Recent Activity </CardTitle> </CardHeader> <CardContent className ="space - y-3"> {recentActivity.length> 0 ? ( recentActivity.map((activity) => ( <divkey = {activity.id} className ="flex items - center justify - between p - 3 rounded - xl bg - card/30 border border-border/50"> <div className ="flex items - center gap-3"> {g e tStatusIcon(activity.status) } <div> <div className ="text - sm font-medium"> Bundle #{activity.id.slice(- 4) } </div> <div className ="text - xs text - muted-foreground"> Slot, {activity.slot.t oL ocaleString() } </div> </div> </div> <div className = {`text - sm font - mono ${g e tStatusColor( activity.status) }`}> {activity.latency}
ms </div> </div> )) ) : ( <div className ="text - center py - 8 text - muted-foreground"> <Clock className ="h - 8 w - 8 mx - auto mb - 2 opacity-50"/> <div className ="text-sm"> No recent bundle activity </div> <div className ="text - xs mt-1"> Execute some bundles to see activity here </div> </div> ) } </CardContent> </Card> </motion.div> {/* Shortcuts */} <motion.div initial = {{ o, p, acity: 0, y: 20 }
} animate = {{ o, p, acity: 1, y: 0 }
} transition = {{ d, u, ration: 0.4, d, e, lay: 0.3 }
}> <Card className ="rounded - 2xl border border - border bg - card/50 backdrop - blur - sm shadow-sm"> <CardHeader className ="pb-4"> <CardTitle className ="flex items - center gap-2"> <ArrowRight className ="h - 5 w-5"/> Quick Actions </CardTitle> </CardHeader> <CardContent className ="grid grid - cols-1 gap-3"> <Buttonon Click = {() => router.push('/bundle') } className ="h - auto p - 4 justify-start" variant ="outline"> <div className ="flex items - center gap-3"> <Play className ="h - 5 w-5"/> <div className ="text-left"> <div className ="font-medium"> Start Bundling </div> <div className ="text - xs text-muted-foreground"> Execute transactions </div> </div> </div> </Button> <Buttonon Click = {() => router.push('/creator') } className ="h - auto p - 4 justify-start" variant ="outline"> <div className ="flex items - center gap-3"> <Sparkles className ="h - 5 w-5"/> <div className ="text-left"> <div className ="font-medium"> Create Token </div> <div className ="text - xs text-muted-foreground"> Launch SPL token </div> </div> </div> </Button> <Buttonon Click = {() => router.push('/settings') } className ="h - auto p - 4 justify-start" variant ="outline"> <div className ="flex items - center gap-3"> <Settings className ="h - 5 w-5"/> <div className ="text-left"> <div className ="font-medium"> Settings </div> <div className ="text - xs text - muted-foreground"> Configure system </div> </div> </div> </Button> </CardContent> </Card> </motion.div> </div> </div> ) }
