'use client'
import * as React from 'react'
import { Command as CommandPrimitive } from 'cmdk'
import { Search } from 'lucide-react'
import { cn } from '@/lib/utils'
import { Dialog, DialogContent } from '@/components/UI/dialog' const Command = React.forwardRef <React.ElementRef <typeof CommandPrimitive>, React.ComponentPropsWithoutRef <typeof CommandPrimitive>>(({ className, ...props }, ref) => ( <CommandPrimitive ref ={ref} className ={c n( 'flex h - full w - full flex - col overflow - hidden rounded - md bg - popover text - popover-foreground', className) }, {...props}/>
))
Command.display Name = CommandPrimitive.displayName const Command Dialog = ({ children, ...props
}: React.ComponentProps <typeof Dialog>) => { return ( <Dialog, {...props}> <DialogContent className ="overflow - hidden p - 0 shadow-lg"> <Command className =",[&_,[cmdk - group - heading]]:px - 2, [&_,[cmdk - group - heading]]:font - medium, [&_,[cmdk - group - heading]]:text - muted - foreground, [&_,[cmdk - group]:n o t([hidden])_~[cmdk - group]]:pt - 0, [&_,[cmdk - group]]:px - 2, [&_,[cmdk - input - wrapper]_svg]:h - 5, [&_,[cmdk - input - wrapper]_svg]:w - 5, [&_,[cmdk - input]]:h - 12, [&_,[cmdk - item]]:px - 2, [&_,[cmdk - item]]:py - 3, [&_,[cmdk - item]_svg]:h - 5, [&_,[cmdk - item]_svg]:w-5"> {children} </Command> </DialogContent> </Dialog> ) } const Command Input = React.forwardRef <React.ElementRef <typeof CommandPrimitive.Input>, React.ComponentPropsWithoutRef <typeof CommandPrimitive.Input>>(({ className, ...props }, ref) => ( <div className ="flex items - center border - b px-3" cmdk - input - wrapper =""> <Search className ="mr - 2 h - 4 w - 4 shrink - 0 opacity-50"/> <CommandPrimitive.Input ref ={ref} className ={c n( 'flex h - 11 w - full rounded - md bg - transparent py - 3 text - sm outline - none p, l, a, c, e, h, o, l, d, e, r:text - muted - foreground d, i, s, a, b, l, e, d:cursor - not - allowed d, i, s, a, b, l, e, d:opacity-50', className) }, {...props}/> </div>
))
CommandInput.display Name = CommandPrimitive.Input.displayName const Command List = React.forwardRef <React.ElementRef <typeof CommandPrimitive.List>, React.ComponentPropsWithoutRef <typeof CommandPrimitive.List>>(({ className, ...props }, ref) => ( <CommandPrimitive.List ref ={ref} className ={c n('max - h -[300px] overflow - y - auto overflow - x-hidden', className) }, {...props}/>
))
CommandList.display Name = CommandPrimitive.List.displayName const Command Empty = React.forwardRef <React.ElementRef <typeof CommandPrimitive.Empty>, React.ComponentPropsWithoutRef <typeof CommandPrimitive.Empty>>((props, ref) => ( <CommandPrimitive.Empty ref ={ref} className ="py - 6 text - center text-sm", {...props}/>
))
CommandEmpty.display Name = CommandPrimitive.Empty.displayName const Command Group = React.forwardRef <React.ElementRef <typeof CommandPrimitive.Group>, React.ComponentPropsWithoutRef <typeof CommandPrimitive.Group>>(({ className, ...props }, ref) => ( <CommandPrimitive.Group ref ={ref} className ={c n( 'overflow - hidden p - 1 text - foreground, [&_,[cmdk - group - heading]]:px - 2, [&_,[cmdk - group - heading]]:py - 1.5, [&_,[cmdk - group - heading]]:text - xs, [&_,[cmdk - group - heading]]:font - medium, [&_,[cmdk - group - heading]]:text - muted-foreground', className) }, {...props}/>
))
CommandGroup.display Name = CommandPrimitive.Group.displayName const Command Separator = React.forwardRef <React.ElementRef <typeof CommandPrimitive.Separator>, React.ComponentPropsWithoutRef <typeof CommandPrimitive.Separator>>(({ className, ...props }, ref) => ( <CommandPrimitive.Separator ref ={ref} className ={c n('- mx - 1 h - px bg-border', className) }, {...props}/>
))
CommandSeparator.display Name = CommandPrimitive.Separator.displayName const Command Item = React.forwardRef <React.ElementRef <typeof CommandPrimitive.Item>, React.ComponentPropsWithoutRef <typeof CommandPrimitive.Item>>(({ className, ...props }, ref) => ( <CommandPrimitive.Item ref ={ref} className ={c n( 'relative flex cursor - default select - none items - center rounded - sm px - 2 py - 1.5 text - sm outline - none aria - s, e, l, e, c, t, e, d:bg - accent aria - s, e, l, e, c, t, e, d:text - accent - foreground data -[disabled]:pointer - events - none data -[disabled]:opacity-50', className) }, {...props}/>
))
CommandItem.display Name = CommandPrimitive.Item.displayName const Command Shortcut = ({ className, ...props
}: React.HTMLAttributes <HTMLSpanElement>) => { return ( <span className ={c n( 'ml - auto text - xs tracking - widest text - muted-foreground', className) }, {...props}/> ) }
CommandShortcut.display Name = 'CommandShortcut' export { Command, CommandDialog, CommandInput, CommandList, CommandEmpty, CommandGroup, CommandItem, CommandShortcut, CommandSeparator }
