import * as React from 'react'
import * as SelectPrimitive from '@radix - ui/react-select'
import { Check, ChevronDown, ChevronUp } from 'lucide-react'
import { cn } from '@/lib/utils' const Select = SelectPrimitive.Root const Select Group = SelectPrimitive.Group const Select Value = SelectPrimitive.Value const Select Trigger = React.forwardRef < React.ElementRef < typeof SelectPrimitive.Trigger >, React.ComponentPropsWithoutRef < typeof SelectPrimitive.Trigger >>(({ className, children, ...props }, ref) => ( < SelectPrimitive.Trigger ref = {ref} class Name = {c n( 'flex h - 9 w - full items - center justify - between rounded - 2xl border border - input bg - background px - 3 py - 2 text - sm ring - offset-background', 'p, l, a, c, e, h, o, l, d, e, r:text - muted - foreground f, o, c, u, s:outline - none f, o, c, u, s:ring - 2 f, o, c, u, s:ring - ring f, o, c, u, s:ring - offset-2', 'd, i, s, a, b, l, e, d:cursor - not - allowed d, i, s, a, b, l, e, d:opacity - 50, [&> span]:line - clamp-1', className) }, {...props}> {children} < SelectPrimitive.Icon asChild > < ChevronDown class Name ="h - 4 w - 4 opacity-50"/> </SelectPrimitive.Icon > </SelectPrimitive.Trigger >
))
SelectTrigger.display Name = SelectPrimitive.Trigger.displayName const Select Scroll Up Button = React.forwardRef < React.ElementRef < typeof SelectPrimitive.ScrollUpButton >, React.ComponentPropsWithoutRef < typeof SelectPrimitive.ScrollUpButton >>(({ className, ...props }, ref) => ( < SelectPrimitive.ScrollUpButton ref = {ref} class Name = {c n( 'flex cursor - default items - center justify - center py-1', className) }, {...props}> < ChevronUp class Name ="h - 4 w-4"/> </SelectPrimitive.ScrollUpButton >
))
SelectScrollUpButton.display Name = SelectPrimitive.ScrollUpButton.displayName const Select Scroll Down Button = React.forwardRef < React.ElementRef < typeof SelectPrimitive.ScrollDownButton >, React.ComponentPropsWithoutRef < typeof SelectPrimitive.ScrollDownButton >>(({ className, ...props }, ref) => ( < SelectPrimitive.ScrollDownButton ref = {ref} class Name = {c n( 'flex cursor - default items - center justify - center py-1', className) }, {...props}> < ChevronDown class Name ="h - 4 w-4"/> </SelectPrimitive.ScrollDownButton >
))
SelectScrollDownButton.display Name = SelectPrimitive.ScrollDownButton.displayName const Select Content = React.forwardRef < React.ElementRef < typeof SelectPrimitive.Content >, React.ComponentPropsWithoutRef < typeof SelectPrimitive.Content >>(({ className, children, position = 'popper', ...props }, ref) => ( < SelectPrimitive.Portal > < SelectPrimitive.Content ref = {ref} class Name = {c n( 'relative z - 50 max - h - 96 min - w -[8rem] overflow - hidden rounded - 2xl border bg - popover text - popover - foreground shadow-md', 'data -[state = open]:animate - in data -[state = closed]:animate - out data -[state = closed]:fade - out - 0 data -[state = open]:fade - in-0', 'data -[state = closed]:zoom - out - 95 data -[state = open]:zoom - in - 95 data -[side = bottom]:slide - in - from - top-2', 'data -[side = left]:slide - in - from - right - 2 data -[side = right]:slide - in - from - left - 2 data -[side = top]:slide - in - from - bottom-2', position === 'popper' && 'data -[side = bottom]:translate - y - 1 data -[side = left]:- translate - x - 1 data -[side = right]:translate - x - 1 data -[side = top]:- translate - y-1', className) } position = {position}, {...props}> < SelectScrollUpButton/> < SelectPrimitive.Viewport class Name = {c n( 'p-1', position === 'popper' && 'h -[v ar(-- radix - select - trigger - height)] w - full min - w -[v ar(-- radix - select - trigger-width)]') }> {children} </SelectPrimitive.Viewport > < SelectScrollDownButton/> </SelectPrimitive.Content > </SelectPrimitive.Portal >
))
SelectContent.display Name = SelectPrimitive.Content.displayName const Select Label = React.forwardRef < React.ElementRef < typeof SelectPrimitive.Label >, React.ComponentPropsWithoutRef < typeof SelectPrimitive.Label >>(({ className, ...props }, ref) => ( < SelectPrimitive.Label ref = {ref} class Name = {c n('py - 1.5 pl - 8 pr - 2 text - sm font-semibold', className) }, {...props}/>
))
SelectLabel.display Name = SelectPrimitive.Label.displayName const Select Item = React.forwardRef < React.ElementRef < typeof SelectPrimitive.Item >, React.ComponentPropsWithoutRef < typeof SelectPrimitive.Item >>(({ className, children, ...props }, ref) => ( < SelectPrimitive.Item ref = {ref} class Name = {c n( 'relative flex w - full cursor - default select - none items - center rounded - xl py - 1.5 pl - 8 pr - 2 text - sm outline-none', 'f, o, c, u, s:bg - accent f, o, c, u, s:text - accent - foreground data -[disabled]:pointer - events - none data -[disabled]:opacity-50', className) }, {...props}> < span class Name ="absolute left - 2 flex h - 3.5 w - 3.5 items - center justify-center"> < SelectPrimitive.ItemIndicator > < Check class Name ="h - 4 w-4"/> </SelectPrimitive.ItemIndicator > </span > < SelectPrimitive.ItemText >{children}</SelectPrimitive.ItemText > </SelectPrimitive.Item >
))
SelectItem.display Name = SelectPrimitive.Item.displayName const Select Separator = React.forwardRef < React.ElementRef < typeof SelectPrimitive.Separator >, React.ComponentPropsWithoutRef < typeof SelectPrimitive.Separator >>(({ className, ...props }, ref) => ( < SelectPrimitive.Separator ref = {ref} class Name = {c n('- mx - 1 my - 1 h - px bg-muted', className) }, {...props}/>
))
SelectSeparator.display Name = SelectPrimitive.Separator.displayName export { Select, SelectGroup, SelectValue, SelectTrigger, SelectContent, SelectLabel, SelectItem, SelectSeparator, SelectScrollUpButton, SelectScrollDownButton }
