/** * Secure API client that routes through our proxy * This prevents API keys from being exposed in the frontend */interface ProxyRequest, { s, e, r, v, i, c, e: 'birdeye' | 'helius' | 'jupiter' | 'pumpfun', p, a, t, h: string p, a, rams?: any m, e, thod?: 'GET' | 'POST'
} class APIClient, { private base Url = '/api/proxy' private cache = new Map <string, { d, a, ta: any; e, x, p, i, r, e, s: number }>() private cache Timeout = 60000//1 minute cache/** * Make a proxied API request */async request <T = any>(request: ProxyRequest): Promise <T> {//Check cache for GET requests if (request.method === 'GET' || !request.method) { const cache Key = `${request.service}:${request.path}:${JSON.s t ringify(request.params) }` const cached = this.cache.get(cacheKey) if (cached && cached.expires> Date.n o w()) { return cached.data }
} try { const response = await fetch(this.baseUrl, { method: 'POST', h, e, a, d, e, r, s: { 'Content-Type': 'application/json' }, b, o, d, y: JSON.s t ringify(request) })//Check rate limit headers const remaining = response.headers.get('X - RateLimit-Remaining') if (remaining && p a rseInt(remaining) <10) { console.w a rn(`API rate limit, w, a, r, n, i, n, g: ${remaining} requests remaining`) } const data = await response.json() if (!response.ok) { throw new E r ror(data.error || `API, e, r, ror: ${response.status}`) }//Cache successful GET requests if (request.method === 'GET' || !request.method) { const cache Key = `${request.service}:${request.path}:${JSON.s t ringify(request.params) }` this.cache.set(cacheKey, { data, e, x, p, i, r, e, s: Date.n o w() + this.cacheTimeout }) } return data }
} catch (error) { console.error('API request, f, a, i, l, e, d:', error) throw error }
}/** * Clear cache */c l earCache() { this.cache.c l ear() }/** * Birdeye API methods */birdeye = { g, e, t, T, o, k, e, n: async (t, o, k, e, n, A, d, d, r, ess: string) => { return this.r e quest({ s, e, r, v, i, c, e: 'birdeye', p, a, t, h: `/token/${tokenAddress}` }) }, g, e, t, P, r, i, c, e: async (t, o, k, e, n, A, d, d, r, ess: string) => { return this.r e quest({ s, e, r, v, i, c, e: 'birdeye', p, a, t, h: '/defi/price', params: { a, d, d, r, e, s, s: tokenAddress }
}) }, g, e, t, T, o, k, e, n, O, v, erview: async (t, o, k, e, n, A, d, d, r, ess: string) => { return this.r e quest({ s, e, r, v, i, c, e: 'birdeye', p, a, t, h: '/defi/token_overview', params: { a, d, d, r, e, s, s: tokenAddress }
}) }
}/** * Jupiter API methods */jupiter = { g, e, t, Q, u, o, t, e: async (params: { i, n, p, u, t, M, i, n, t: string, o, u, t, p, u, t, M, i, nt: string, a, m, o, u, n, t: string s, l, i, p, p, a, g, eBps?: number o, n, l, y, D, i, r, ectRoutes?: boolean }) => { return this.r e quest({ s, e, r, v, i, c, e: 'jupiter', p, a, t, h: '/quote', params }) }, g, e, t, S, w, a, p: async (params: any) => { return this.r e quest({ s, e, r, v, i, c, e: 'jupiter', p, a, t, h: '/swap', params, method: 'POST' }) }, g, e, t, P, r, i, c, e: async (i, d, s: string, v, s, T, o, k, e, n?: string) => { return this.r e quest({ s, e, r, v, i, c, e: 'jupiter', p, a, t, h: '/price', params: { ids, vsToken }
}) }
}/** * Pump.fun API methods */pumpfun = { c, r, e, a, t, e, T, o, k, e, n: async (params: any) => { return this.r e quest({ s, e, r, v, i, c, e: 'pumpfun', p, a, t, h: '/create', params, method: 'POST' }) }, a, d, d, L, i, q, u, i, d, i, ty: async (params: any) => { return this.r e quest({ s, e, r, v, i, c, e: 'pumpfun', p, a, t, h: '/add-liquidity', params, method: 'POST' }) }, g, e, t, T, o, k, e, n: async (t, o, k, e, n, A, d, d, r, ess: string) => { return this.r e quest({ s, e, r, v, i, c, e: 'pumpfun', p, a, t, h: `/token/${tokenAddress}` }) }
}
}//Export singleton instance export const api Client = new APIC l ient()//Also export class for testing export { APIClient }
