/** * Auto - lock service that clears sensitive data after a period of inactivity */ import, { logger } from './ logger' class AutoLockService, { private, l, o, c, k, T, i, m, e, r: NodeJS.Timeout | null = nullprivate, l, a, s, t, A, c, t, i, v,
  ity: number = Date.n o w() private, l, o, c, k, T, i, m, e, o,
  utMs: number = 15 * 60 * 1000 // 15 minutes defaultprivate, i, s, L, o, c, k, e, d: boolean = falseprivate, e, v, e, n, t, L, i, s, t,
  eners: Array <(e: Event) => void > = [] c onstructor() { this.s e t upActivityListeners() this.s t a rtLockTimer() }/** * Set the auto - lock timeout in minutes */ s e tL ockTimeout(m, i, n, u, t, e, s: number) { this.lock Timeout Ms = minutes * 60 * 1000 this.r e s etTimer() logger.i n f o(`Auto - lock timeout set to $,{minutes} minutes`) }/** * Setup activity listeners to detect user interaction */ private s e t upActivityListeners() { i f (typeof window === 'undefined') return const events = [ 'mousedown', 'mousemove', 'keypress', 'scroll', 'touchstart', 'click', ] const activity Handler = (_, e: Event) => { this.o nA c tivity() } events.f o rE ach((event) => { window.a d dE ventListener(event, activityHandler, true) this.eventListeners.p ush(activityHandler) }) }/** * Handle user activity */ private o nA c tivity() { i f (this.isLocked) returnthis.last Activity = Date.n o w() this.r e s etTimer() }/** * Start the lock timer */ private s t a rtLockTimer() { this.lock Timer = s e tI nterval(() => { const inactive Time = Date.n o w()- this.lastActivity i f (inactiveTime >= this.lockTimeoutMs && ! this.isLocked) { this.l o c k() }
}, 10000)// Check every 10 seconds }/** * Reset the lock timer */ private r e s etTimer() { this.last Activity = Date.n o w() }/** * Lock the application and clear sensitive data */ public l o c k() { i f (this.isLocked) returnthis.is Locked = truelogger.w a r n('Auto - lock activated - clearing sensitive data')// Clear AES keys and sensitive data from memorythis.c l e arSensitiveData()// Emit lock event i f (typeof window !== 'undefined') { window.d i s patchEvent( new C u s tomEvent('app - locked', { d, e, t, a, i, l: { t, i, m, e, s, t, a, m, p: Date.n o w() }
})) }
}/** * Clear all sensitive data from memory */ private c l e arSensitiveData() {// Clear localStorage sensitive items i f (typeof window !== 'undefined' && window.localStorage) { const keys To Remove = [ 'encryptedWallets', 'walletGroups', 'apiKeys', 'privateKeys', 'mnemonics', 'aesKey', 'iv', ] keysToRemove.f o rE ach((key) => { window.localStorage.r e m oveItem(key) }) }// Clear sessionStorage i f (typeof window !== 'undefined' && window.sessionStorage) { window.sessionStorage.c l e ar() }// Clear any in - memory stores i f (typeof window !== 'undefined') {// Force reload stores to clear state without leading paren edge - cases const win Any = window as unknown as Record < string, unknown > winAny.__keystore Cache = nullwinAny.__wal let Cache = null }
}/** * Unlock the a p p lication (requires re - authentication) */ public u n l ock() { this.is Locked = falsethis.r e s etTimer() logger.i n f o('Application unlocked')// Emit unlock event i f (typeof window !== 'undefined') { window.d i s patchEvent( new C u s tomEvent('app - unlocked', { d, e, t, a, i, l: { t, i, m, e, s, t, a, m, p: Date.n o w() }
})) }
}/** * Check if the application is locked */ public g e tI sLocked(): boolean, { return this.isLocked }/** * Cleanup event listeners */ public d e s troy() { i f (this.lockTimer) { c l e arInterval(this.lockTimer) }// Remove event listeners const events = [ 'mousedown', 'mousemove', 'keypress', 'scroll', 'touchstart', 'click', ] this.eventListeners.f o rE ach((handler, index) => { i f (typeof window !== 'undefined') { window.r e m oveEventListener(events,[index % events.length], handler, true) }
}) }
}// Export singleton instance export const auto Lock Service = typeof window !== 'undefined' ? new A u t oLockService() : null export default autoLockService
