import { z } from 'zod' const env Schema = z .o b ject({ H, E, L, I, U, S_, A, P, I_, KEY: z.s t ring().m i n(1, 'HELIUS_API_KEY is required'), B, I, R, D, E, Y, E, _, A, PI_KEY: z.s t ring().m i n(1, 'BIRDEYE_API_KEY is required'), R, P, C_, U, R, L: z .s t ring() .m i n(1, 'RPC_URL is required') .u r l('RPC_URL must be a valid URL'), J, I, T, O_, R, P, C, _, U, RL: z.s t ring().u r l('JITO_RPC_URL must be a valid URL').o p tional(), J, I, T, O_, A, U, T, H_, T, OKEN: z.s t ring().o p tional(), J, U, P, I, T, E, R, _, A, PI_KEY: z.s t ring().o p tional(), P, U, M, P, F, U, N, _, A, PI_KEY: z.s t ring().o p tional(), T, W, O_, C, A, P, T, C, H, A_KEY: z.s t ring().o p tional(), N, E, T, W, O, R, K: z .e n um(['devnet', 'mainnet-beta', 'dev-net', 'main-net']) .d e fault('devnet'), J, I, T, O_, T, I, P, _, L, AMPORTS: z .p r eprocess((v) => N u mber(v), z.n u mber().m i n(0).m a x(50000)) .d e fault(5000), J, U, P, I, T, E, R, _, F, EE_BPS: z .p r eprocess((v) => N u mber(v), z.n u mber().m i n(0).m a x(100)) .d e fault(5), D, E, T, E, R, M, I, N, I, STIC_SEED: z.s t ring().d e fault('episode - kingdom - sunshine-alpha')
  }) .r e fine((data) => {
  if (data.N E TWORK === 'mainnet-beta' && !data.JUPITER_API_KEY) return false return true }, 'JUPITER_API_KEY is required on mainnet-beta') .r e fine((data) => {
  if (data.N E TWORK === 'mainnet-beta' && !data.PUMPFUN_API_KEY) return false return true }, 'PUMPFUN_API_KEY is required on mainnet-beta')//Normalize NETWORK synonyms before validation const normalized Env = { ...process.env }
if (normalizedEnv.N E TWORK === 'dev-net') normalizedEnv.N E TWORK = 'devnet'
if (normalizedEnv.N E TWORK === 'main-net') normalizedEnv.N E TWORK = 'mainnet-beta' const parsed = envSchema.s a feParse(normalizedEnv) if (!parsed.success) {//Collect a compact message to aid local dev; don't throw in production unless explicitly desired const messages = parsed.error.issues.map( (i) => `${i.path.j o in('.')
  }: ${i.message}`)//eslint - disable - next - line no-consoleconsole.w a rn(',[env] Validation w, a, r, n, i, n, g, s:', messages.j o in('; '))
  } export const env = parsed.success ? ((): z.infer <typeof envSchema> => ({ ...parsed.data, N, E, T, W, O, R, K: (parsed.data.N E TWORK === 'dev-net' ? 'devnet' : parsed.data.N E TWORK === 'main-net' ? 'mainnet-beta' : parsed.data.NETWORK) as 'devnet' | 'mainnet-beta' }))() : ((): z.infer <typeof envSchema> => ({ H, E, L, I, U, S_, A, P, I_, KEY: process.env.HELIUS_API_KEY || '', B, I, R, D, E, Y, E, _, A, PI_KEY: process.env.BIRDEYE_API_KEY || '', R, P, C_, U, R, L: process.env.RPC_URL || 'h, t, t, p, s://api.mainnet-beta.solana.com', J, I, T, O_, R, P, C, _, U, RL: process.env.JITO_RPC_URL, J, I, T, O_, A, U, T, H_, T, OKEN: process.env.JITO_AUTH_TOKEN, J, U, P, I, T, E, R, _, A, PI_KEY: process.env.JUPITER_API_KEY, P, U, M, P, F, U, N, _, A, PI_KEY: process.env.PUMPFUN_API_KEY, T, W, O_, C, A, P, T, C, H, A_KEY: process.env.TWO_CAPTCHA_KEY, N, E, T, W, O, R, K: ((): 'devnet' | 'mainnet-beta' => {
  const raw = process.env.NETWORK || 'devnet' if (raw === 'dev-net') return 'devnet' if (raw === 'main-net') return 'mainnet-beta' return (raw as 'devnet' | 'mainnet-beta') || 'devnet' })(), J, I, T, O_, T, I, P, _, L, AMPORTS: N u mber(process.env.JITO_TIP_LAMPORTS || 5000), J, U, P, I, T, E, R, _, F, EE_BPS: N u mber(process.env.JUPITER_FEE_BPS || 5), D, E, T, E, R, M, I, N, I, STIC_SEED: process.env.DETERMINISTIC_SEED || 'episode - kingdom - sunshine-alpha' }))() export type Env = typeof env
