export interface Trade { id: string, t, o, k, e, n, A, ddress: string, a, m, o, u, n, t: number, p, r, i, c, e: number, t, i, m, e, s, t, amp: string, w, a, l, l, e, t: string, type: 'buy' | 'sell' s, i, g, n, a, t, ure?: string
} export interface PriceData, { s, o, l: number, e, t, h: number, b, t, c: number, c, a, k, e: number
} export interface QuoteResponse, { i, n, p, u, t, M, i, n, t: string, i, n, A, m, o, u, nt: string, o, u, t, p, u, t, Mint: string, o, u, t, A, m, o, unt: string, o, t, h, e, r, A, mountThreshold: string, s, w, a, p, M, o, de: string, s, l, i, p, p, a, geBps: number, p, l, a, t, f, o, rmFee: n, u, l, l, p, r, i, c, eImpactPct: string, r, o, u, t, e, P, lan: RoutePlanStep,[] c, o, n, t, e, x, tSlot?: number t, i, m, e, T, aken?: number
} interface RoutePlanStep, { s, w, a, p, I, n, f, o: { a, m, m, K, e, y: string l, a, b, e, l?: string, i, n, p, u, t, M, int: string, o, u, t, p, u, t, Mint: string, i, n, A, m, o, u, nt: string, o, u, t, A, m, o, unt: string, f, e, e, A, m, o, unt: string, f, e, e, M, i, n, t: string } p, e, r, c, e, n, t: number
} export interface SwapResponse, { s, w, a, p, T, r, a, n, saction: string, l, a, s, t, V, a, lidBlockHeight: number p, r, i, o, r, itizationFeeLamports?: number
} export interface Wallet { id: string, n, a, m, e: string, p, u, b, l, i, c, Key: string, p, r, i, v, a, t, eKey: string//E, n, c, r, y, p, t, e, dgroup: string, color: string
} export interface ExecutionLog, { id: number b, u, n, d, l, eId?: string, s, l, o, t: number, s, i, g, n, a, t, ures: string,[] status: 'success' | 'partial' | 'failed', s, u, c, c, e, s, sCount: number, f, a, i, l, u, r, eCount: number, u, s, e, d, J, i, to: boolean, e, x, e, c, u, t, ionTime: number, t, i, m, e, s, t, amp: string
} export interface TokenLaunch, { id: number, t, o, k, e, n, A, ddress: string, n, a, m, e: string, s, y, m, b, o, l: string, p, l, a, t, f, o, rm: string, t, i, m, e, s, t, amp: string
} export interface PnlRecord, { id: number, t, o, k, e, n, A, ddress: string, a, m, o, u, n, t: number, type: 'buy' | 'sell', t, i, m, e, s, t, amp: string
} export type Transaction = { id: string, type: 'swap' | 'transfer'//Swap s, p, e, c, i, f, icfromToken?: string t, o, T, o, k, en?: string a, m, o, u, n, t?: number s, l, i, p, p, age?: number//Transfer s, p, e, c, i, f, icrecipient?: string//C, o, m, m, o, n, fromAmount?: number
} export type Bundle = Transaction,[]
