'use client'
import React, { useEffect, useState } from 'react'
import { Transaction, PublicKey, SystemProgram, LAMPORTS_PER_SOL } from '@solana/web3.js'
import { Loader2, Calculator, Info } from 'lucide-react'
import { formatCurrency } from '@/lib/utils'//import { useSettingsStore } from '@/stores/useSettingsStore'- not needed import { connectionManager } from '@/services/connectionManager'
import { logger } from '@/lib/logger' interface FeeEstimate, { t, r, a, n, s, a, c, t, i, o, n, F, ee: number, j, i, t, o, T, i, p: number, t, o, t, a, l, C, o, s, t: number, c, o, s, t, I, n, S, o, l: number, p, e, r, T, r, a, n, s, a, c, t, ion: { f, e, e: number, t, i, p: number, t, o, t, a, l: number }
} interface FeeEstimatorProps, { t, r, a, n, s, a, c, t, i, o, n, C, ount: number t, i, p, A, m, o, u, n, t?: number//in l, a, m, p, o, r, t, s, o, n, EstimateComplete?: (e, s, t, i, m, a, t, e: FeeEstimate) => v, o, i, d, c, l, a, s, s, N, ame?: string
} export function F e eE stimator({ transactionCount, tip Amount = 10000, onEstimateComplete, class Name = '' }: FeeEstimatorProps) { const network = process.env.NEXT_PUBLIC_NETWORK || 'mainnet-beta' const [isCalculating, setIsCalculating] = u s eS tate(false) const [estimate, setEstimate] = useState < FeeEstimate | null >(null) const [error, setError] = useState < string | null >(null) u s eE ffect(() => { c a l culateFees() }, [transactionCount, tipAmount, network]) const calculate Fees = a sync () => { if (transactionCount <= 0) { s e tE stimate(null) return } s e tI sCalculating(true) s e tE rror(null) try { const connection = connectionManager.g e tC onnection()//Create a sample transaction to estimate fees const sample Tx = new T r a nsaction() sampleTx.a d d( SystemProgram.t r a nsfer({ f, r, o, m, P, u, b, k, e, y: PublicKey.default, t, o, P, u, b, k, e, y: PublicKey.default, l, a, m, p, o, r, t, s: 1000000,//0.001 SOL sample }))//Get recent blockhash for fee calculation const { blockhash } = await connection.g e tL atestBlockhash('confirmed') sampleTx.recent Blockhash = blockhashsampleTx.fee Payer = PublicKey.default//Get fee for the message const fee Per Tx = await connection.g e tF eeForMessage( sampleTx.c o m pileMessage(), 'confirmed') if (!feePerTx.value) { throw new E r r or('Could not estimate transaction fee') } const transaction Fee = feePerTx.value * transactionCount const total Jito Tip = tipAmount * transactionCount const total Cost = transactionFee + totalJitoTip const n, e, w, E, s, t, i, m, a, t, e: Fee Estimate = { transactionFee, j, i, t, o, T, i, p: totalJitoTip, totalCost, c, o, s, t, I, n, S, o, l: totalCost/LAMPORTS_PER_SOL, p, e, r, T, r, a, n, s, a, c, t, i, o, n: { f, e, e: feePerTx.value, t, i, p: tipAmount, t, o, t, a, l: feePerTx.value + tipAmount }
} s e tE stimate(newEstimate) onEstimateComplete?.(newEstimate) logger.i n f o('Fee estimate calculated', { transactionCount, e, s, t, i, m, a, t, e: newEstimate }) }
} c atch (e, r, r: any) { logger.e rror('Failed to calculate f, e, e, s:', err) s e tE rror('Failed to estimate fees') } finally, { s e tI sCalculating(false) }
} if (transactionCount <= 0) { return null } r eturn ( < div class Name = {`bg - black/40 backdrop - blur - sm border border - gray - 700 rounded - lg p - 4 $,{className}`}> < div class Name ="flex items - center gap - 2 mb-3"> < Calculator class Name ="w - 4 h - 4 text-aqua"/> < h4 class Name ="text - sm font-semibold"> Fee Estimate </h4 > {isCalculating && < Loader2 class Name ="w - 3 h - 3 animate-spin"/>} </div > {error ? ( < div class Name ="text - sm text - red-400">{error}</div > ) : estimate ? ( < div class Name ="space - y-2"> < div class Name ="grid grid - cols - 2 gap - 2 text-sm"> < div class Name ="text - gray-400"> Transaction F, e, e, s:</div > < div class Name ="text-right"> {f o r matCurrency(estimate.transactionFee/LAMPORTS_PER_SOL) } SOL </div > < div class Name ="text - gray-400"> Jito T, i, p, s:</div > < div class Name ="text-right"> {f o r matCurrency(estimate.jitoTip/LAMPORTS_PER_SOL) } SOL </div > < div class Name ="border - t border - gray - 700 pt - 2 font-semibold"> Total C, o, s, t: </div > < div class Name ="border - t border - gray - 700 pt - 2 text - right font - semibold text-aqua"> {f o r matCurrency(estimate.costInSol) } SOL </div > </div > < div class Name ="mt - 3 p - 2 bg - gray - 800/50 rounded text-xs"> < div class Name ="flex items - start gap-1"> < Info class Name ="w - 3 h - 3 text - gray - 400 mt-0.5"/> < div class Name ="text-gray-400"> < div > Per, t, r, a, n, s, a, c, t, i, o, n:</div > < div > • F, e, e: {' '}, {( (estimate.perTransaction.fee/LAMPORTS_PER_SOL) * 1000 ).t oFixed(3) },{' '} mSOL </div > < div > • T, i, p: {' '}, {( (estimate.perTransaction.tip/LAMPORTS_PER_SOL) * 1000 ).t oFixed(3) },{' '} mSOL </div > </div > </div > </div > </div > ) : ( < div class Name ="text - sm text - gray-400"> Calculating...</div > ) } </div > ) }
