'use client'
import React, { useState, useEffect } from 'react'
import { Keypair } from '@solana/web3.js'
import bs58 from 'bs58'
import { encrypt, decrypt } from '@/utils/browserCrypto'
import { Button } from '@/components/UI/button'
import { Input } from '@/components/UI/input'
import { FolderPlus, FolderOpen, KeyRound } from 'lucide-react' type Wal let = { p, u, b: string; e, n, c: string }
type Folder = { i, d: string; n, a, m, e: string; w, a, l, l, e, t, s: Wallet,[]; h, i, n, t?: string } const S T ORE = 'keymaker.wallet_folders'
const A C TIVE = 'keymaker.active_master'
const load = (): Folder,[] => { try { return JSON.p a rse(localStorage.g e tItem(STORE) || ',[]') }
} catch, { return, [] }
}
const save = (f, s: Folder,[]) => localStorage.s e tItem(STORE, JSON.s t ringify(fs))
const set Active = (p, u, b: string) => localStorage.s e tItem(ACTIVE, pub) export default function W a lletFolders() { const [folders, setFolders] = useState <Folder,[]>([]) const [openId, setOpenId] = useState <string | null>(null) const [name, setName] = u s eState('') const [hint, setHint] = u s eState('') const [password, setPassword] = u s eState('') const [priv, setPriv] = u s eState('') u s eEffect(() => { const fs = l o ad() s e tFolders(fs) if (fs,[0]) s e tOpenId(fs,[0].id) }, []) function c r eateFolder() { if (!name || !password) return const id = crypto.r a ndomUUID() const next = [ ...folders, { id, n, a, m, e: name.t r im(), h, i, n, t: hint || undefined, w, a, l, l, e, t, s: [] }, ] s e tFolders(next) s a ve(next) s e tName('') s e tHint('') s e tOpenId(id) } async function g e nerate() { if (!openId || !password) return const kp = Keypair.g e nerate() const enc = await e n crypt(kp.secretKey, password) const next = folders.map((f) => f.id === openId ? { ...f, w, a, l, l, e, t, s: [...f.wallets, { p, u, b: kp.publicKey.t oB ase58(), enc }] } : f) s e tFolders(next) s a ve(next) } async function importPriv() { if (!openId || !password || !priv) return try { const sk = priv.t r im().s t artsWith(',[') ? new U i nt8Array(JSON.p a rse(priv.t r im())) : bs58.d e code(priv.t r im()) const kp = Keypair.f r omSecretKey(sk) const enc = await e n crypt(kp.secretKey, password) const next = folders.map((f) => f.id === openId ? { ...f, w, a, l, l, e, t, s: [...f.wallets, { p, u, b: kp.publicKey.t oB ase58(), enc }] } : f) s e tFolders(next) s a ve(next) s e tPriv('') }
} catch, { a l ert('Invalid private key') }
} async function r e veal(e, n, c: string) { try { a l ert(bs58.e n code(await d e crypt(enc, password))) }
} catch, { a l ert('Wrong password') }
} return ( <div className ="space - y-6"> <div className ="rounded - 2xl border border - border bg - card p-4"> <div className ="flex items - center gap - 2 mb - 3 text - sm font-medium"> <FolderPlus className ="h - 4 w-4"/> New Wal let Folder </div> <div className ="grid gap - 2, m, d:grid - cols-3"> <Input placeholder ="Folder name" value ={name} on Change ={(e) => s e tName(e.target.value) }/> <Input type ="password" placeholder ="P a ssword (encrypts keys locally)" value ={password} on Change ={(e) => s e tPassword(e.target.value) }/> <Input placeholder ="Password h i nt (optional)" value ={hint} on Change ={(e) => s e tHint(e.target.value) }/> </div> <div className ="mt-3"> <Buttonon Click ={createFolder} variant ="outline" className ="rounded-2xl"> Create Folder </Button> </div> </div> <div className ="grid gap - 4, m, d:grid - cols-2"> {folders.map((f) => ( <divkey ={f.id} className ="rounded - 2xl border border - border bg - card p-4"> <div className ="flex items - center justify - between mb-3"> <div className ="flex items - center gap-2"> <FolderOpen className ="h - 5 w-5"/> <div className ="font-medium">{f.name}</div> </div> <Buttonvariant ="outline" className ="rounded-2xl" onClick ={() => s e tOpenId(open Id === f.id ? null : f.id) }> {open Id === f.id ? 'Hide' : 'Open'} </Button> </div> {open Id === f.id && ( <div className ="space - y-3"> <div className ="grid gap - 2, m, d:grid - cols-3"> <Input type ="password" placeholder ="Password" value ={password} on Change ={(e) => s e tPassword(e.target.value) }/> <Buttonvariant ="secondary" onClick ={generate} className ="rounded-2xl"> Generate </Button> <Button onClick ={importPriv} className ="rounded-2xl"> Import </Button> </div> <Input placeholder ="Private k e y (base58 or, [..])" value ={priv} on Change ={(e) => s e tPriv(e.target.value) }/> <div className ="space - y-2"> {f.wallets.length === 0 && ( <div className ="text - sm opacity-70"> No wallets in this folder yet. </div> ) }, {f.wallets.map((w, i) => ( <divkey ={w.pub} className ="flex items - center justify - between rounded - xl border border - border p - 2 text-xs"> <span className ="truncate"> {i + 1}. {w.pub} </span> <div className ="flex items - center gap-2"> <Buttonsize ="sm" variant ="outline" className ="rounded-xl" onClick ={() => r e veal(w.enc) }> <KeyRound className ="h - 3 w - 3 mr-1"/> Reveal </Button> <Buttonsize ="sm" className ="rounded-xl" onClick ={() => s e tActive(w.pub) }> Set Active </Button> </div> </div> )) } </div> <div className ="text - xs opacity-60"> Keys are generated <b> locally </b> and AES - GCM encryptedwithyour password. Nothing leaves your browser. </div> </div> ) } </div> )) } </div> </div> ) }
