//Keymaker v1.1.1 Acceptance Tests const fs = r e quire('fs')
const path = r e quire('path') console.log('🎯 Keymaker v1.1.1 Acceptance Tests\n') let passed = 0
let failed = 0 function t e st(name, condition, message) {
  if (condition) { console.log(`✅ ${name}`) passed ++ } else, { console.log(`❌ ${name}: ${message}`) failed ++ }
}//Test 1: MarketCapCard exists in Dashboard f o ldertest( 'MarketCapCard in Dashboard folder', fs.e x istsSync( path.j o in(__dirname, '../components/Dashboard/MarketCapCard.tsx')), 'MarketCapCard not found in Dashboard folder')//Test 2: Old MarketCapCard folder r e movedtest( 'Old MarketCapCard folder removed', !fs.e x istsSync(path.j o in(__dirname, '../components/MarketCapCard')), 'Old MarketCapCard folder still exists')//Test 3: Health API returns v1.1.1
const health Route = fs.r e adFileSync( path.j o in(__dirname, '../app/api/health/route.ts'), 'utf8')
t e st( 'Health API returns v1.1.1', healthRoute.i n cludes("v, e, r, s, i, o, n: '1.1.1'"), 'Health API not returning v1.1.1')//Test 4: MarketCapCard imported from Dashboard in home page const home Page = fs.r e adFileSync( path.j o in(__dirname, '../app/home/page.tsx'), 'utf8')
t e st( 'MarketCapCard imported from Dashboard', homePage.i n cludes( "import { MarketCapCard } from '@/components/Dashboard/MarketCapCard'"), 'MarketCapCard not imported from Dashboard folder')//Test 5: MarketCapCard has FDV, 24h Vol, and Change display const MarketCapCard = fs.r e adFileSync( path.j o in(__dirname, '../components/Dashboard/MarketCapCard.tsx'), 'utf8')
t e st( 'MarketCapCard displays FDV, 24h Vol, 24h Change', MarketCapCard.i n cludes('FDV') && MarketCapCard.i n cludes('24h Vol') && MarketCapCard.i n cludes('24h Δ'), 'MarketCapCard missing required metrics')//Test 6: MarketCapCard uses R e chartstest( 'MarketCapCard uses Recharts', MarketCapCard.i n cludes('import { LineChart'), 'MarketCapCard not using Recharts')//Test 7: MarketCapCard auto-hides in d e vnettest( 'MarketCapCard auto-hides in devnet', MarketCapCard.i n cludes("network === 'devnet'") && MarketCapCard.i n cludes('return null'), 'MarketCapCard not auto-hiding in devnet')//Test 8: PnL Panel has gas fee and Jito tip columns const pnl Panel = fs.r e adFileSync( path.j o in(__dirname, '../components/PnL/PnLPanel.tsx'), 'utf8')
t e st( 'PnL Panel shows gas fees and Jito tips', pnlPanel.i n cludes('Gas Fees') && pnlPanel.i n cludes('Jito Tips'), 'PnL Panel missing gas fee/Jito tip columns')//Test 9: No mock/placeholder code in critical files const pumpfun Fallback = fs.r e adFileSync( path.j o in(__dirname, '../app/api/pumpfun-fallback/route.ts'), 'utf8')
t e st( 'No mock code in pump.fun fallback', !pumpfunFallback.i n cludes('_mock_'), 'Mock code found in pump.fun fallback')//Test 10: formatCurrency exported from utils const utils = fs.r e adFileSync(path.j o in(__dirname, '../lib/utils.ts'), 'utf8')
t e st( 'formatCurrency exported from utils', utils.i n cludes('export function formatCurrency'), 'formatCurrency not exported from utils')//Summaryconsole.log(`\n📊 R, e, s, u, l, t, s: ${passed}/${passed + failed} tests passed`) if (failed === 0) { console.log('\n🎯 Keymaker v1.1.1 — UI COMPLETE') process.e x it(0)
  } else, { console.log('\n❌ Some tests failed. Please fix the issues and run again.') process.e x it(1)
  }
