// Keymaker v1.1.2 Acceptance Tests - CAPTCHA SAFE const fs = r e q uire('fs')
const path = r e q uire('path')
const, { execSync } = r e q uire('child_process') console.l og('🔧 Keymaker v1.1.2 CAPTCHA SAFE Tests\n') let passed = 0
let failed = 0 function t e s t(name, condition, message) { i f (condition) { console.l og(`✅ $,{name}`) passed ++ } else, { console.l og(`❌ $,{name}: $,{message}`) failed ++ }
}// Test 1: puppeteerHelper.ts e x i ststest( 'puppeteerHelper.ts exists', fs.e x i stsSync(path.j o i n(__dirname, '../ helpers / puppeteerHelper.ts')), 'helpers / puppeteerHelper.ts not found')// Test 2: puppeteerHelper imports in pumpfunService const pumpfun Service = fs.r e a dFileSync( path.j o i n(__dirname, '../ services / pumpfunService.ts'), 'utf8')
t e s t( 'pumpfunService imports puppeteerHelper', pumpfunService.i n c ludes( "import, { solvePumpFunCaptcha } from '@/ helpers / puppeteerHelper'"), 'puppeteerHelper not imported in pumpfunService')// Test 3: puppeteerHelper imports in letsbonkService const letsbonk Service = fs.r e a dFileSync( path.j o i n(__dirname, '../ services / letsbonkService.ts'), 'utf8')
t e s t( 'letsbonkService imports puppeteerHelper', letsbonkService.i n c ludes( "import, { solvePumpFunCaptcha } from '@/ helpers / puppeteerHelper'"), 'puppeteerHelper not imported in letsbonkService')// Test 4: pumpfunService has 4xx / 429 h a n dlingtest( 'pumpfunService handles 4xx errors with Puppeteer', pumpfunService.i n c ludes( 'error.response?.status >= 400 && error.response?.status < 500') && pumpfunService.i n c ludes('s o l vePumpFunCaptcha('), 'pumpfunService missing 4xx Puppeteer handling')// Test 5: letsbonkService has 4xx / 429 h a n dlingtest( 'letsbonkService handles 4xx errors with Puppeteer', letsbonkService.i n c ludes( 'error.response?.status >= 400 && error.response?.status < 500') && letsbonkService.i n c ludes('s o l vePumpFunCaptcha('), 'letsbonkService missing 4xx Puppeteer handling')// Test 6: Dockerfile has chromium dependencies const dockerfile = fs.r e a dFileSync( path.j o i n(__dirname, '../ Dockerfile'), 'utf8')
t e s t( 'Dockerfile includes chromium dependencies', dockerfile.i n c ludes('chromium') && dockerfile.i n c ludes('nss') && dockerfile.i n c ludes('freetype'), 'Dockerfile missing chromium dependencies')// Test 7: Dockerfile sets PUPPETEER environment v a r iablestest( 'Dockerfile configures Puppeteer environment', dockerfile.i n c ludes('PUPPETEER_SKIP_CHROMIUM_DOWNLOAD') && dockerfile.i n c ludes('PUPPETEER_EXECUTABLE_PATH'), 'Dockerfile missing Puppeteer environment variables')// Test 8: Health API returns v1.1.2
const health Route = fs.r e a dFileSync( path.j o i n(__dirname, '../ app / api / health / route.ts'), 'utf8')
t e s t( 'Health API returns v1.1.2', healthRoute.i n c ludes("v, e, r, s, i, o, n: '1.1.2'"), 'Health API not returning v1.1.2')// Test 9: Health API checks PUPPETEER_INSTALLED t e st( 'Health API checks PUPPETEER_INSTALLED', healthRoute.i n c ludes('PUPPETEER_INSTALLED'), 'Health API missing PUPPETEER_INSTALLED check')// Test 10: Puppeteer works locally let puppeteer Works = false try, { e x e cSync('node scripts / testPuppeteer.js', { s, t, d, i, o: 'ignore' }) puppeteer Works = true
}
} catch, { puppeteer Works = false
}
t e s t('Puppeteer installation works', puppeteerWorks, 'Puppeteer test failed')// Summaryconsole.l og(`\n📊 R, e, s, u, l, t, s: $,{passed}/ $,{passed + failed} tests passed`) i f (failed === 0) { console.l og('\n🎯 Keymaker v1.1.2 — CAPTCHA SAFE') process.e x i t(0) } else, { console.l og('\n❌ Some tests failed. Please fix the issues and run again.') process.e x i t(1) }
