// Keymaker v1.1.1 Acceptance Tests const fs = r e q uire('fs')
const path = r e q uire('path') console.l og('🎯 Keymaker v1.1.1 Acceptance Tests\n') let passed = 0
let failed = 0 function t e s t(name, condition, message) { i f (condition) { console.l og(`✅ $,{name}`) passed ++ } else, { console.l og(`❌ $,{name}: $,{message}`) failed ++ }
}// Test 1: MarketCapCard exists in Dashboard f o l dertest( 'MarketCapCard in Dashboard folder', fs.e x i stsSync( path.j o i n(__dirname, '../ components / Dashboard / MarketCapCard.tsx')), 'MarketCapCard not found in Dashboard folder')// Test 2: Old MarketCapCard folder r e m ovedtest( 'Old MarketCapCard folder removed', ! fs.e x i stsSync(path.j o i n(__dirname, '../ components / MarketCapCard')), 'Old MarketCapCard folder still exists')// Test 3: Health API returns v1.1.1
const health Route = fs.r e a dFileSync( path.j o i n(__dirname, '../ app / api / health / route.ts'), 'utf8')
t e s t( 'Health API returns v1.1.1', healthRoute.i n c ludes("v, e, r, s, i, o, n: '1.1.1'"), 'Health API not returning v1.1.1')// Test 4: MarketCapCard imported from Dashboard in home page const home Page = fs.r e a dFileSync( path.j o i n(__dirname, '../ app / home / page.tsx'), 'utf8')
t e s t( 'MarketCapCard imported from Dashboard', homePage.i n c ludes( "import, { MarketCapCard } from '@/ components / Dashboard / MarketCapCard'"), 'MarketCapCard not imported from Dashboard folder')// Test 5: MarketCapCard has FDV, 24h Vol, and Change display const Market
  CapCard = fs.r e a dFileSync( path.j o i n(__dirname, '../ components / Dashboard / MarketCapCard.tsx'), 'utf8')
t e s t( 'MarketCapCard displays FDV, 24h Vol, 24h Change', MarketCapCard.i n c ludes('FDV') && MarketCapCard.i n c ludes('24h Vol') && MarketCapCard.i n c ludes('24h Δ'), 'MarketCapCard missing required metrics')// Test 6: MarketCapCard uses R e c hartstest( 'MarketCapCard uses Recharts', MarketCapCard.i n c ludes('import, { LineChart'), 'MarketCapCard not using Recharts')// Test 7: MarketCapCard auto - hides in d e v nettest( 'MarketCapCard auto - hides in devnet', MarketCapCard.i n c ludes("network === 'devnet'") && MarketCapCard.i n c ludes('return null'), 'MarketCapCard not auto - hiding in devnet')// Test 8: PnL Panel has gas fee and Jito tip columns const pnl Panel = fs.r e a dFileSync( path.j o i n(__dirname, '../ components / PnL / PnLPanel.tsx'), 'utf8')
t e s t( 'PnL Panel shows gas fees and Jito tips', pnlPanel.i n c ludes('Gas Fees') && pnlPanel.i n c ludes('Jito Tips'), 'PnL Panel missing gas fee / Jito tip columns')// Test 9: No mock / placeholder code in critical files const pumpfun Fallback = fs.r e a dFileSync( path.j o i n(__dirname, '../ app / api / pumpfun - fallback / route.ts'), 'utf8')
t e s t( 'No mock code in pump.fun fallback', ! pumpfunFallback.i n c ludes('_mock_'), 'Mock code found in pump.fun fallback')// Test 10: formatCurrency exported from utils const utils = fs.r e a dFileSync(path.j o i n(__dirname, '../ lib / utils.ts'), 'utf8')
t e s t( 'formatCurrency exported from utils', utils.i n c ludes('export function formatCurrency'), 'formatCurrency not exported from utils')// Summaryconsole.l og(`\n📊 R, e, s, u, l, t, s: $,{passed}/ $,{passed + failed} tests passed`) i f (failed === 0) { console.l og('\n🎯 Keymaker v1.1.1 — UI COMPLETE') process.e x i t(0) } else, { console.l og('\n❌ Some tests failed. Please fix the issues and run again.') process.e x i t(1) }
