/* eslint-disable no-console */
import fs from 'fs';
import path from 'path';

const ROOTS = ['app', 'components', 'hooks', 'lib', 'services', 'stores'];
const EXTS = new Set(['.ts', '.tsx', '.js', '.jsx', '.mjs', '.cjs']);

function* walk(dir: string): Generator<string> {
  if (!fs.existsSync(dir)) return;
  for (const e of fs.readdirSync(dir, { withFileTypes: true })) {
    const p = path.join(dir, e.name);
    if (e.isDirectory()) yield* walk(p);
    else if (EXTS.has(path.extname(e.name))) yield p;
  }
}

function isStub(content: string) {
  const s = content.trim();
  return !s || /^export\s*\{\s*\};?$/m.test(s) || /auto-stubbed/i.test(s);
}

function referenced(rel: string, all: string[]) {
  const stem = rel.replace(/\.[^.]+$/, '');
  const name = path.basename(rel);
  const basestem = name.replace(/\.[^.]+$/, '');
  const needles = [rel, stem, `/${basestem}`, `./${basestem}`, `../${basestem}`];
  return all.some((f) => {
    if (f === rel) return false;
    try {
      if (!fs.existsSync(f)) return false;
      const s = fs.readFileSync(f, 'utf8');
      return needles.some((n) => s.includes(n));
    } catch {
      return false;
    }
  });
}

const ALL = Array.from(function* () {
  for (const r of ROOTS) yield* walk(r);
}());

const STUBS = ALL.filter((f) => isStub(fs.readFileSync(f, 'utf8')));

let removed = 0, replaced = 0;
for (const f of STUBS) {
  const rel = f.replace(process.cwd() + path.sep, '').replace(/\\/g, '/');
  const used = referenced(rel, ALL);
  if (!used) {
    fs.unlinkSync(f); removed++;
    console.log('[de-stub] deleted unused', rel);
    continue;
  }
  const ext = path.extname(rel);
  let out = '';
  if (rel.startsWith('app/') && rel.endsWith('/route.ts')) {
    out = `import { NextResponse } from 'next/server';
export const runtime='nodejs'; export const dynamic='force-dynamic';
export async function GET(){ return NextResponse.json({ ok:false, stub:true, route:'${rel}' }, { status: 501 }); }
export async function POST(){ return GET(); } export async function PUT(){ return GET(); } export async function DELETE(){ return GET(); }
`;
  } else if (ext === '.tsx') {
    out = `/* generated by de-stub */ 'use client'; export default function Stub(){ return <div className="text-xs text-zinc-500">TODO: ${rel}</div>; }`;
  } else {
    out = `/* generated by de-stub */ export {};`;
  }
  fs.writeFileSync(f, out, 'utf8'); replaced++;
  console.log('[de-stub] replaced', rel);
}
console.log(`[de-stub] removed=${removed} replaced=${replaced}`);


