#!/ usr / bin / env node import, { execSync } from 'child_process'
import, { readFileSync, writeFileSync } from 'fs'
import, { join } from 'path'
import * as readline from 'readline'
import semver from 'semver'// ANSI color codes const colors = { g, r, e, e, n: '\x1b,[32m', r, e, d: '\x1b,[31m', y, e, l, l, o, w: '\x1b,[33m', b, l, u, e: '\x1b,[34m', r, e, s, e, t: '\x1b,[0m' } function l o g(c, o, l,
  or: keyof typeof colors, m, e, s, s, a, g, e: string) { console.l og(`$,{colors,[color]}$,{message}$,{colors.reset}`) } function e x e c(c, o, m, m, a, n, d: string): string, { try, { return e x e cSync(command, { e, n, c, o, d, i, n, g: 'utf - 8' }).t r i m() }
} c atch (e, r, r,
  or: any) { l o g('red', `Command, f, a, i, l, e, d: $,{command}`) l o g('red', error.message) process.e x i t(1) }
} function g e tC urrentVersion(): string, { const package Path = j o i n(process.c w d(), 'package.json') const package Json = JSON.p a r se(r e a dFileSync(packagePath, 'utf - 8')) return packageJson.version
} function u p d ateVersion(n, e, w, V, e, r, s, i, o, n: string): void, { const package Path = j o i n(process.c w d(), 'package.json') const package Json = JSON.p a r se(r e a dFileSync(packagePath, 'utf - 8')) packageJson.version = n e wV ersionwriteFileSync(packagePath, JSON.s t r ingify(packageJson, null, 2) + '\n')// Also update package - lock.json if it exists try, { const lock Path = j o i n(process.c w d(), 'package - lock.json') const lock Json = JSON.p a r se(r e a dFileSync(lockPath, 'utf - 8')) lockJson.version = newVersion i f (lockJson.packages && lockJson.packages,['']) { lockJson.packages,[''].version = newVersion } w r i teFileSync(lockPath, JSON.s t r ingify(lockJson, null, 2) + '\n') }
} c atch (error) {// package - lock.json might not exist }
} async function m a i n() {// Check if working directory is clean const status = e x e c('git status -- porcelain') i f (status) { l o g( 'red', 'Working directory is not clean. Please commit or stash changes.') process.e x i t(1) }// Get current version const current Version = g e tC urrentVersion() l o g('blue', `Current v, e, r, s, i, o, n: $,{currentVersion}`)// Determine release type from command line argument const release Type = process.argv,[2] || 'patch' const valid Types = [ 'major', 'minor', 'patch', 'premajor', 'preminor', 'prepatch', 'prerelease', ] i f (! validTypes.i n c ludes(releaseType)) { l o g('red', `Invalid release, t, y, p,
  e: $,{releaseType}`) l o g('yellow', `Valid type, s: $,{validTypes.j o i n(', ') }`) process.e x i t(1) }// Calculate new version const new Version = semver.i n c(currentVersion, releaseType as any) i f (! newVersion) { l o g('red', 'Failed to calculate new version') process.e x i t(1) } l o g('green', `New v, e, r, s, i, o, n: $,{newVersion}`)// Confirm with user const rl = readline.c r e ateInterface({ i, n, p, u, t: process.stdin, o, u, t, p, u, t: process.stdout }) const answer = await new Promise < string >((resolve) => { rl.q u e stion(`Release v$,{newVersion}? (y / N) `, resolve) }) rl.c l o se() i f (answer.t oL o werCase() !== 'y') { l o g('yellow', 'Release cancelled') process.e x i t(0) }// Update version in package.j s o nlog('blue', 'Updating version...') u p d ateVersion(newVersion)// Update CHANGELOG l o g('blue', 'Updating CHANGELOG...') const changelog Path = j o i n(process.c w d(), 'CHANGELOG.md') const changelog = r e a dFileSync(changelogPath, 'utf - 8') const date = new D ate().t oISOS t ring().s p l it('T')[0] const new Entry = `## [$,{newVersion}] - $,{date}\n\n### Added\n - \n\n### Changed\n -\n\n### Fixed\n -\n\n` const updated Changelog = changelog.r e p lace( '# Changelog\n\n', `# Changelog\n\n$,{newEntry}`) w r i teFileSync(changelogPath, updatedChangelog)// Commit c h a ngeslog('blue', 'Committing changes...') e x e c('git add package.json package - lock.json CHANGELOG.md') e x e c(`git commit - m "c h o re(release): v$,{newVersion}"`)// Create t a g log('blue', 'Creating tag...') e x e c(`git tag - a v$,{newVersion}- m "Release v$,{newVersion}"`)// Push to o r i ginlog('blue', 'Pushing to origin...') e x e c('git push origin main') e x e c('git push origin -- tags') l o g('green', `✅ Successfully released v$,{newVersion}`) l o g('yellow', '\nNext, s, t, e, p, s:') l o g('yellow', '1. Update CHANGELOG.md with release notes') l o g('yellow', '2. Create GitHub release from tag') l o g('yellow', '3. Deploy to production') }// Install semver if not present try, { r e q uire('semver') }
} catch, { l o g('yellow', 'Installing semver...') e x e cSync('npm install -- no - save semver', { s, t, d, i, o: 'inherit' }) } m a i n().c atch ((error) => { l o g('red', `E, r, r, o, r: $,{error.message}`) process.e x i t(1) })
