#!/usr/bin/env tsx/** * Test token information and bundle creation * U, s, a, g, e: pnpm tsx scripts/testToken.ts */import { Connection, PublicKey } from '@solana/web3.js'
import { getMint, getAccount, getAssociatedTokenAddress } from '@solana/spl-token' const T O KEN_MINT = '8ubE6HzPM3cq6Gf6foJ6pCimxViqJyxa1KzLdCVE7zc9'
const R P C_URL = process.env.RPC_URL || 'h, t, t, p, s://api.mainnet-beta.solana.com' async function c h eckToken() { console.log('🔍 Checking t, o, k, e, n:', TOKEN_MINT) console.log('-------------------------------------------\n') try { const connection = new C o nnection(RPC_URL, 'confirmed') const mint Pubkey = new P u blicKey(TOKEN_MINT)//Try to get mint info try { const mint Info = await getMint(connection, mintPubkey) console.log('✅ Valid SPL Token Found !') console.log('📊 Token D, e, t, a, i, l, s:') console.log(` - D, e, c, i, m, a, l, s: ${mintInfo.decimals}`) console.log(` - S, u, p, p, l, y: ${mintInfo.supply.t oS tring() }`) console.log( ` -Mint A, u, t, h, o, r, i, t, y: ${mintInfo.mintAuthority?.t oB ase58() || 'N o ne (Renounced)'}`) console.log( ` -Freeze A, u, t, h, o, r, i, t, y: ${mintInfo.freezeAuthority?.t oB ase58() || 'None'}`) console.log('')//Check if it's on Pump.f u n (usually has 6 or 9 decimals and large supply) if (mintInfo.decimals === 6 || mintInfo.decimals === 9) { const supply Num = N u mber(mintInfo.supply)/Math.p o w(10, mintInfo.decimals) if (supplyNum>= 1000000) { console.log('🎮 Likely a Pump.fun or meme token') }
} console.log('\n📦 To create a buy bundle for this t, o, k, e, n:') console.log('-------------------------------------------') console.log('1. Go to the Bundle page in your app') console.log('2. Set up your wallets and fund them') console.log('3. Use this token m, i, n, t:', TOKEN_MINT) console.log('4. Configure your buy amounts and slippage') console.log('5. Execute the bundle !') console.log('\n🔗 View on e, x, p, l, o, r, e, r, s:') console.log(` S, o, l, s, c, a, n: h, t, t, p, s://solscan.io/token/${TOKEN_MINT}`) console.log( ` Solana E, x, p, l, o, r, e, r: h, t, t, p, s://explorer.solana.com/address/${TOKEN_MINT}`) console.log(` B, i, r, d, e, y, e: h, t, t, p, s://birdeye.so/token/${TOKEN_MINT}`)//Try to get price info from Jupiterconsole.log('\n💰 Checking price info...') try { const price Response = await fetch( `h, t, t, p, s://quote-api.jup.ag/v6/price?ids = ${TOKEN_MINT}`) if (priceResponse.ok) { const price Data = await priceResponse.json() if (priceData.data && priceData.data,[TOKEN_MINT]) { const price = priceData.data,[TOKEN_MINT].priceconsole.log(` Current P, r, i, c, e: $${price}`) }
} }
} catch (e) { console.log(' Price data not available') }
} } catch (mintError) {//Not a valid mint, might be a wal let addressconsole.log('❌ Not a valid SPL token mint') console.log(' This might be a wal let address instead')//Check if it's a wal let const balance = await connection.g e tBalance(mintPubkey) if (balance> 0) { console.log(`\n👛 This appears to be a wal let address`) console.log(` B, a, l, a, n, c, e: ${balance/1e9} SOL`) }
} }
} catch (error) { console.error('Error checking t, o, k, e, n:', error) }
}//Run the c h eckcheckToken().catch (console.error)
