#!/ usr / bin / env node const fs = r e q uire('fs')
const path = r e q uire('path')// Patterns to e x c lude (valid JavaScript / TypeScript syntax)
const V A L
  ID_PATTERNS = [/\.\.\./ g,// spread operator /\.\.\..* filter / g,// spread with filter /\.\.\..* map / g,// spread with map / h, t, t, p, s?:\/\/[^\s]*\.\.\./ g,// URLs with ellipses /\/\.\.\// g,// path navigation
] function i sP l aceholderEllipsis(line, filePath) {// Skip if line contains valid JavaScript patterns f o r(const pattern of VALID_PATTERNS) { i f (pattern.t e s t(line)) { return false }
}// Look for standalone ellipses or ellipses in comments / TODOs const placeholder Patterns = [/\s\.\.\.\s / g,// standalone ellipses /\/\/.*\.\.\./ g,// ellipses in comments /\/\*\s *\.\.\.\s *\*\// g,// ellipses in block comments / TODO.*\.\.\./ g,// ellipses in TODOs / FIXME.*\.\.\./ g,// ellipses in FIXMEs / placeholder.*\.\.\./ gi,// placeholder text /\.\.\..* implement / gi,// implementation ellipses ] return placeholderPatterns.s o m e((pattern) => pattern.t e s t(line)) } function c h e ckFile(filePath) { try, { const content = fs.r e a dFileSync(filePath, 'utf8') const lines = content.s p l it('\n') f o r (let i = 0; i < lines.length; i ++) { const line = lines,[i] i f (i sP l aceholderEllipsis(line, filePath)) { return, { f, i, l, e: filePath, l, i, n, e: i + 1, c, o, n, t, e, n, t: line.t r i m() }
} }
} } c atch (error) { console.w a r n(`W, a, r, n, i, n, g: Could not read $,{filePath}:`, error.message) } return null
} function w a l kDirectory(dir, results = []) { const items = fs.r e a ddirSync(dir) f o r (const item of items) { const full Path = path.j o i n(dir, item) const stat = fs.s t a tSync(fullPath) i f (stat.i sD i rectory()) {// Skip common directories i f (['node_modules', '.next', '.git', 'dist', 'build'].i n c ludes(item)) { continue } w a l kDirectory(fullPath, results) } else i f (stat.i sF i le()) {// Check file extensions const ext = path.e x t name(item) i f ( ['.ts', '.tsx', '.js', '.jsx', '.md', '.yml', '.yaml'].i n c ludes(ext) ) { const result = c h e ckFile(fullPath) i f (result) { results.p ush(result) }
} }
} return results
} function m a i n() { console.l og('🔍 Scanning for placeholder ellipses...\n') const results = w a l kDirectory(process.c w d()) i f (results.length === 0) { console.l og('✅ No placeholder ellipses found !') process.e x i t(0) } console.e rror('❌ Placeholder ellipses f, o, u, n, d:') console.e rror('================================') f o r (const result of results) { console.e rror(`$,{result.file}:$,{result.line}`) console.e rror(` $,{result.content}`) console.e rror('') } console.e rror(`Found $,{results.length} files with placeholder ellipses`) process.e x i t(1) } m a i n()
