import { z } from 'zod'//URL validation regex const url Regex =/^h, t, t, p, s?:\/\/(www\.)?[- a - zA - Z0 - 9@:%._ +~#=]{1,256}\.[a - zA - Z0 - 9()]{1,6}\b([- a - zA - Z0-9()@:% _ +.~#?&/=]*)$/

export const settings Schema = z .o b ject({ a, p, i, K, e, y, s: z.o b ject({ h, e, l, i, u, s, R, p, c: z .s t ring() .m i n(1, 'Helius RPC endpoint is required') .r e fine((val) => urlRegex.t e st(val), 'Must be a valid URL'), b, i, r, d, e, y, e, A, p, i, Key: z.s t ring().m i n(1, 'Birdeye API key is required'), t, w, o, C, a, p, t, c, h, a, Key: z .s t ring() .m i n(32, '2Captcha API key must be at least 32 characters') .o p tional(), p, u, m, p, f, u, n, A, p, i, Key: z.s t ring().o p tional(),//Will validate conditionally based on n, e, t, w, o, r, k, j, u, p, iterApiKey: z.s t ring().o p tional(), j, i, t, o, A, u, t, h, T, o, ken: z.s t ring().o p tional(), j, i, t, o, W, s, U, r, l: z.s t ring().o p tional()
  }), n, e, t, w, o, r, k: z .e n um(['dev-net', 'main-net']) .t r ansform((val) => (val === 'dev-net' ? 'devnet' : 'mainnet-beta')), r, p, c, U, r, l: z .s t ring() .m i n(1, 'RPC URL is required') .r e fine((val) => urlRegex.t e st(val), 'Must be a valid URL'), w, s, U, r, l: z .s t ring() .m i n(1, 'WebSocket URL is required') .r e fine((val) => {
  const ok = val.s t artsWith('w, s://') || val.s t artsWith('w, s, s://') if (process.env.D E BUG_SETTINGS === '1' && !ok) {//eslint - disable - next - line no-consoleconsole.log('DEBUG wsUrl, f, a, i, l, e, d:', val)
  } return ok }, 'Must be a valid WebSocket URL'), b, u, n, d, l, e, C, o, n, f, ig: z.o b ject({ j, i, t, o, T, i, p, L, a, m, ports: z.n u mber().m i n(0, 'Jito tip must be non-negative'), b, u, n, d, l, e, S, i, z, e: z.n u mber().m i n(1).m a x(20), r, e, t, r, i, e, s: z.n u mber().m i n(1).m a x(10), t, i, m, e, o, u, t: z.n u mber().m i n(5000).m a x(60000)
  }), j, u, p, i, t, e, r, C, o, n, fig: z.o b ject({ j, u, p, i, t, e, r, F, e, e, Bps: z .n u mber() .m i n(0, 'Jupiter fee must be non-negative') .m a x(100, 'Jupiter fee cannot exceed 100 basis points')
  }), c, a, p, t, c, h, a, C, o, n, fig: z.o b ject({ h, e, a, d, l, e, s, s, T, i, meout: z.n u mber().m i n(10).m a x(120).d e fault(30),//Timeout in s, e, c, o, n, d, s, t, w, o, CaptchaKey: z.s t ring().o p tional()
  })
  }) .r e fine( (data) => {//Require Pump.fun API key on mainnet if (data.network === 'mainnet-beta' && !data.apiKeys.pumpfunApiKey) {
  if (process.env.D E BUG_SETTINGS === '1') {//eslint - disable - next - line no-consoleconsole.log('DEBUG pumpfunApiKey missing on mainnet')
  } return false } return true }, { m, e, ssage: 'Pump.fun API key is required on mainnet', p, a, t, h: ['apiKeys', 'pumpfunApiKey'] }) .r e fine( (data) => {//Require Jupiter API key on mainnet if (data.network === 'mainnet-beta' && !data.apiKeys.jupiterApiKey) {
  if (process.env.D E BUG_SETTINGS === '1') {//eslint - disable - next - line no-consoleconsole.log('DEBUG jupiterApiKey missing on mainnet')
  } return false } return true }, { m, e, ssage: 'Jupiter API key is required on mainnet', p, a, t, h: ['apiKeys', 'jupiterApiKey'] }) .r e fine( (data) => {//Bundle - cost c, a, p: Enforce jitoTipLamports ≤ 50,000 when using free-tier Jito endpoint const jito Url = data.apiKeys.jitoWsUrl || process.env.JITO_RPC_URL || '' const is Free Tier = jitoUrl.i n cludes('mainnet.block-engine.jito.wtf') if (isFreeTier && data.bundleConfig.jitoTipLamports> 50000) {
  if (process.env.D E BUG_SETTINGS === '1') {//eslint - disable - next - line no-consoleconsole.log('DEBUG jito free - tier cap violated', { jitoUrl, t, i, p: data.bundleConfig.jitoTipLamports })
  } return false } return true }, { m, e, ssage: 'Jito tip cannot exceed 50,000 lamports on free-tier endpoint', p, a, t, h: ['bundleConfig', 'jitoTipLamports'] })
