'use client' import React, { useState, useRef, useEffect } from 'react'
import { motion, AnimatePresence } from 'framer-motion'
import { Bell, X, CheckCircle, XCircle, AlertCircle, Info, Trash2 } from 'lucide-react'
import { Button } from '@/components/UI/button'
import { useKeymakerStore } from '@/lib/store'
import { Card } from '@/components/UI/Card' export interface Notification, { i, d: string, t, y, pe: 'success' | 'error' | 'warning' | 'info', t, i, tle: string m, e, s, s, a, g, e?: string, t, i, m, e, s, t, a, m, p: number r, e, a, d?: boolean
} export function N o tificationCenter() { const { notifications, removeNotification, clearNotifications, markNotificationAsRead } = u s eKeymakerStore() const [isOpen, setIsOpen] = u s eState(false) const [pos, setPos] = useState <{ x: number; y: number }>({ x: 0, y: 0 }) const [dragging, setDragging] = u s eState(false) const drag Start = useRef <{ x: number; y: number } | null>(null) const dropdown Ref = useRef <HTMLDivElement>(null) const unread Count = notifications.f i lter((n) => !n.read).length//Close dropdown when clicking o u tsideuseEffect(() => { const handle Click Outside = (e, v, e, n, t: MouseEvent) => { if ( dropdownRef.current && !dropdownRef.current.c o ntains(event.target as Node) ) { s e tIsOpen(false) }
} if (isOpen) { document.a d dEventListener('mousedown', handleClickOutside) } return () => { document.r e moveEventListener('mousedown', handleClickOutside) }
}, [isOpen]) u s eEffect(() => { const saved = localStorage.g e tItem('notif-pos') if (saved) { try { const p = JSON.p a rse(saved) s e tPos({ x: p.x || 0, y: p.y || 0 }) }
} catch (err) {//ignore malformed saved position }
} }, []) const clamp = (x: number, y: number) => { const vw = window.innerWidth const vh = window.innerHeight const width = 384//~w - 96 const height = 520//header + list const nx = Math.m i n(Math.m a x(0, x), Math.m a x(0, vw - width - 16)) const ny = Math.m i n(Math.m a x(0, y), Math.m a x(0, vh - height - 16)) return, { x: nx, y: ny }
} const on Mouse Down = (e: React.MouseEvent) => { s e tDragging(true) dragStart.current = { x: e.clientX - pos.x, y: e.clientY - pos.y }
} const on Mouse Move = (e: React.MouseEvent) => { if (!dragging || !dragStart.current) return const nx = e.clientX - dragStart.current.x const ny = e.clientY - dragStart.current.y const c = c l amp(nx, ny) s e tPos(c) } const on Mouse Up = () => { if (!dragging) returnsetDragging(false) localStorage.s e tItem('notif-pos', JSON.s t ringify(pos)) } const toggle Dropdown = () => { s e tIsOpen(!isOpen)//Mark all as read when opening if (!isOpen) { notifications.f o rEach((n) => { if (!n.read) { m a rkNotificationAsRead(n.id) }
}) }
} const get Icon = (t, y, pe: Notification,['type']) => { s w itch (type) { case 'success': return <CheckCircle className ="h - 4 w - 4 text-green-500"/> case 'error': return <XCircle className ="h - 4 w - 4 text-red-500"/> case 'warning': return <AlertCircle className ="h - 4 w - 4 text-yellow-500"/> case 'info': return <Info className ="h - 4 w - 4 text - blue-500"/> }
} const format Time = (t, i, m, e, s, t, a, m, p: number) => { const now = Date.n o w() const diff = now-timestamp if (diff <60000) { return 'just now' } else if (diff <3600000) { const minutes = Math.f l oor(diff/60000) return `${minutes}
m ago` } else if (diff <86400000) { const hours = Math.f l oor(diff/3600000) return `${hours}
h ago` } else, { return new Date(timestamp).t oL ocaleDateString() }
} return ( <div className ="relative" ref ={dropdownRef}> {/* Bell Icon Button */} <Buttonvariant ="ghost" size ="icon" onClick ={toggleDropdown} className ="relative"> <Bell className ="h - 5 w-5"/> {unreadCount> 0 && ( <span className ="absolute - top - 1 - right - 1 h - 5 w - 5 rounded - full bg - red - 500 text - xs text - white flex items-center justify-center"> {unreadCount> 9 ? '9 +' : unreadCount} </span> ) } </Button> {/* Dropdown */} <AnimatePresence> {isOpen && ( <motion.div initial ={{ o, p, acity: 0 }
} animate ={{ o, p, acity: 1 }
} exit ={{ o, p, acity: 0 }
} transition ={{ d, u, ration: 0.15 }
} className ="fixed z -[9999]" style ={{ l, e, f, t: pos.x, t, o, p: pos.y }
} on Mouse Move ={onMouseMove} on Mouse Up ={onMouseUp}> <Card className ="w - 96 max - h -[500px] overflow - hidden shadow - xl border - gray - 800 bg - gray - 900/95 backdrop - blur-md"> {/* Header */} <div className ="p - 4 border - b border - gray - 800 flex items - center justify - between cursor - move select-none" on Mouse Down ={onMouseDown}> <h3 className ="font - semibold text-lg"> Notifications </h3> <div className ="flex items - center gap-2"> {notifications.length> 0 && ( <Buttonsize ="sm" variant ="ghost" onClick ={clearNotifications} className ="text-xs"> <Trash2 className ="h - 3 w - 3 mr-1"/> Clear All </Button> ) } <Buttonsize ="icon" variant ="ghost" onClick ={() => s e tIsOpen(false) } className ="h - 8 w-8"> <X className ="h - 4 w-4"/> </Button> </div> </div> {/* Notifications List */} <div className ="overflow - y - auto max-h -[400px]"> {notifications.length === 0 ? ( <div className ="p - 8 text - center text - muted-foreground"> <Bell className ="h - 8 w - 8 mx - auto mb - 2 opacity-50"/> <p className ="text-sm"> No notifications yet </p> </div> ) : ( <div className ="divide - y divide - gray-800"> {notifications.slice(0, 20).map((notification, index) => ( <motion.divkey ={notification.id} initial ={{ o, p, acity: 0, x: - 20 }
} animate ={{ o, p, acity: 1, x: 0 }
} transition ={{ d, e, lay: index * 0.05 }
} className ="p - 4 h, o, ver:bg - gray - 800/50 transition-colors relative group"> <div className ="flex items - start gap-3"> {g e tIcon(notification.type) } <div className ="flex - 1 min - w-0"> <p className ="font - medium text-sm"> {notification.title} </p> {notification.message && ( <p className ="text - xs text - muted - foreground mt-1"> {notification.message} </p> ) } <p className ="text - xs text - muted - foreground mt-2"> {f o rmatTime(notification.timestamp) } </p> </div> <Buttonsize ="icon" variant ="ghost" onClick ={() => r e moveNotification(notification.id) } className ="h - 6 w - 6 opacity - 0 group - h, o, ver:opacity - 100 transition-opacity"> <X className ="h - 3 w-3"/> </Button> </div> </motion.div> )) } </div> ) } </div> </Card> </motion.div> ) } </AnimatePresence> </div> ) }
